apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: keycloak-realm-import
spec:
  keycloakCRName: keycloak
  realm:
    id: "eb865181-ed0d-4a16-86d1-000000000000"
    realm: "publicground"
    enabled: true

    users:
      - id: "eb865181-ed0d-4a16-86d2-000000000001"
        username: "medewerkergzac"
        enabled: true
        email: "medewerkergzac@example.com"
        firstName: "Medewerker"
        lastName: "Gzac"
        credentials:
          - type: "password"
            value: "${MEDEWERKER_GZAC_PASSWORD}" # Verwijst naar env var in de Keycloak pod
            temporary: false
        realmRoles:
          - "ROLE_USER"
      - id: "eb865181-ed0d-4a16-86d2-000000000002"
        username: "admingzac"
        enabled: true
        email: "admingzac@example.com"
        firstName: "Admin"
        lastName: "Gzac"
        credentials:
          - type: "password"
            value: "${ADMIN_GZAC_PASSWORD}" # Verwijst naar env var in de Keycloak pod
            temporary: false
        realmRoles:
          - "ROLE_USER"
          - "ROLE_ADMIN"
      - id: "eb865181-ed0d-4a16-86d2-000000000003"
        username: "adminopenzaak"
        enabled: true
        email: "adminopenzaak@example.com"
        firstName: "Open"
        lastName: "Zaak Admin"
        emailVerified: true
        credentials:
          - type: password
            value: "${ADMIN_OPENZAAK_PASSWORD}"
            temporary: false
        clientRoles:
          openzaak:
            - "Admin"
      - id: "eb865181-ed0d-4a16-86d2-000000000004"
        username: "adminopennotificaties"
        enabled: true
        email: "adminopennotificaties@example.com"
        firstName: "Open"
        lastName: "Notificaties Admin"
        emailVerified: true
        credentials:
          - type: password
            value: "${ADMIN_OPENNOTIFICATIES_PASSWORD}"
            temporary: false
        clientRoles:
          opennotificaties:
            - "OPENNOTIFICATIES_ADMIN"
      - id: "eb865181-ed0d-4a16-86d2-000000000005"
        username: "adminopenobjecten"
        enabled: true
        email: "adminopenobjecten@example.com"
        firstName: "Open"
        lastName: "Objecten Admin"
        emailVerified: true
        credentials:
          - type: password
            value: "${ADMIN_OPENOBJECTEN_PASSWORD}"
            temporary: false
        clientRoles:
          openobjecten:
            - "OPENOBJECTEN_ADMIN"

    clients:
      - id: "eb865181-ed0d-4a16-86d3-000000000001"
        clientId: "gzac-frontend"
        name: "gzac frontend"
        enabled: true
        protocol: "openid-connect"
        publicClient: true
        redirectUris:
          - "https://gzac.wigo4it.nl/*"
          - "http://gzac.wigo4it.nl/*"
        webOrigins:
          - "https://gzac.wigo4it.nl"
          - "http://gzac.wigo4it.nl"
        standardFlowEnabled: true
        directAccessGrantsEnabled: true
      - id: "eb865181-ed0d-4a16-86d3-000000000002"
        clientId: "gzac-backend"
        name: "gzac backend"
        enabled: true
        protocol: "openid-connect"
        clientAuthenticatorType: "client-secret"
        secret: "${GZAC_BACKEND_APP_CLIENT_SECRET}" # Verwijst naar env var in de Keycloak pod
        redirectUris:
          - "https://gzac.wigo4it.nl/*"
          - "http://gzac.wigo4it.nl/*"
        webOrigins:
          - "https://gzac.wigo4it.nl"
          - "http://gzac.wigo4it.nl"
        publicClient: false
        standardFlowEnabled: false
        implicitFlowEnabled: false
        directAccessGrantsEnabled: false
        serviceAccountsEnabled: true
      - id: "eb865181-ed0d-4a16-86d3-000000000003"
        clientId: "openzaak"
        name: "openzaak"
        enabled: true
        protocol: "openid-connect"
        clientAuthenticatorType: "client-secret"
        secret: "${OPENZAAK_APP_CLIENT_SECRET}" # Verwijst naar env var in de Keycloak pod
        redirectUris:
          - "https://openzaak.wigo4it.nl/oidc/callback/"
          - "http://openzaak.wigo4it.nl/oidc/callback/"
        webOrigins:
          - "https://openzaak.wigo4it.nl"
          - "http://openzaak.wigo4it.nl"
        publicClient: false
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: false
        # roles:
        #   - name: Admin
        #     clientRole: true
        #     description: "Admin rol voor OpenZaak"
        protocolMappers:
          - name: "oz-client-roles-mapper-to-roles-claim"
            protocol: openid-connect
            protocolMapper: oidc-usermodel-client-role-mapper
            consentRequired: false
            config:
              claim.name: "roles"
              id.token.claim: "true"
              access.token.claim: "true"
              usermodel.clientRoleMapping.clientId: "openzaak"
              multivalued: "true"
              jsonType.label: "String"
      - id: "eb865181-ed0d-4a16-86d3-000000000004"
        clientId: "opennotificaties"
        name: "opennotificaties"
        enabled: true
        protocol: "openid-connect"
        clientAuthenticatorType: "client-secret"
        secret: "${OPENNOTIFICATIES_APP_CLIENT_SECRET}" # Verwijst naar env var in de Keycloak pod
        redirectUris:
          - "https://opennotificaties.wigo4it.nl/oidc/callback/"
          - "http://opennotificaties.wigo4it.nl/oidc/callback/"
        webOrigins:
          - "https://opennotificaties.wigo4it.nl"
          - "http://opennotificaties.wigo4it.nl"
        publicClient: false
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: false
        protocolMappers:
          - name: "on-client-roles-mapper-to-roles-claim"
            protocol: openid-connect
            protocolMapper: oidc-usermodel-client-role-mapper
            consentRequired: false
            config:
              claim.name: "roles"
              id.token.claim: "true"
              access.token.claim: "true"
              usermodel.clientRoleMapping.clientId: "opennotificaties"
              multivalued: "true"
              jsonType.label: "String"
      - id: "eb865181-ed0d-4a16-86d3-000000000005"
        clientId: "openobjecten"
        name: "openobjecten"
        enabled: true
        protocol: "openid-connect"
        clientAuthenticatorType: "client-secret"
        secret: "${OPENOBJECTEN_APP_CLIENT_SECRET}" # Verwijst naar env var in de Keycloak pod
        redirectUris:
          - "https://openobjecten.wigo4it.nl/oidc/callback/"
          - "http://openobjecten.wigo4it.nl/oidc/callback/"
        webOrigins:
          - "https://openobjecten.wigo4it.nl"
          - "http://openobjecten.wigo4it.nl"
        publicClient: false
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: true
        serviceAccountsEnabled: false
        protocolMappers:
          - name: "oo-client-roles-mapper-to-roles-claim"
            protocol: openid-connect
            protocolMapper: oidc-usermodel-client-role-mapper
            consentRequired: false
            config:
              claim.name: "roles"
              id.token.claim: "true"
              access.token.claim: "true"
              usermodel.clientRoleMapping.clientId: "openobjecten"
              multivalued: "true"
              jsonType.label: "String"

    roles:
      realm:
        - id: "eb865181-ed0d-4a16-86d4-000000000001"
          name: "ROLE_USER"
          description: "Standaard gzac gebruikersrol."
        - id: "eb865181-ed0d-4a16-86d4-000000000002"
          name: "ROLE_ADMIN"
          description: "Standaard gzac beheerdersrol"
      client:
        openzaak:
          - id: "eb865181-ed0d-4a16-86d5-000000000001"
            name: Admin
            clientRole: true
            description: "Admin rol voor OpenZaak"
        opennotificaties:
          - id: "eb865181-ed0d-4a16-86d6-000000000001"
            name: OPENNOTIFICATIES_ADMIN
            clientRole: true
            description: "Admin rol voor OpenNotificaties"
        openobjecten:
          - id: "eb865181-ed0d-4a16-86d7-000000000001"
            name: OPENOBJECTEN_ADMIN
            clientRole: true
            description: "Admin rol voor OpenObjecten"
      # clientRoles:
      #   realm-management:
      #     - name: "view-users"
      #       description: "${role_view-users}"
      #       clientRole: true
      #       containerId: "realm-management" # ID of naam van de realm-management client
      #     - name: "view-realm"
      #       description: "${role_view-realm}"
      #       clientRole: true
      #       containerId: "realm-management"

    scopeMappings:
      - client: "gzac-backend"
        roles:
          - "realm-management/view-users"
          - "realm-management/view-realm"
