---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openproduct
  namespace: publicground
spec:
  encryptedData:
    OPENPRODUCT_SUPERUSER_PASSWORD: AgAL2C8va5HcwgWr584iDeGk34fBIGajSvcmoOomjZB/XR3qbfNfA/I3kgYc1f8F1qgW4E4ZB+lu4nGP/s7U7HJYmJQZ+t/ZSJquxnGmnf9SoL1+UhnE8JFeIqP0600KgUF9bFecJWqbsBUS5uvMmc7klZHLV3B+WFpTqaociigtfckhXYu6paoys5pEXsQ5kBsZQoZeAdBhd4aeEPO4j4GMo5LE9hYTdAjqS2per+/nyeiBs9IReXpiopwjT2L7R4/Z4pGldC+SQwVzE+QkyXLP2dDkhQ4b2X3tBZxgjw/0WlVe1WSvF/vp2/hsmW8Ke1IaEuSq2UNGPXB0RsWQhanGrSoJr1HfJKghHQ3T/+Z7XWuxGj5JWNGzKLOLZQuEMLQC/iXiIk/E1i+XfMKuJQLUMzYLrZtQhu4WUSTFa/dPzFZE3NTUuWElt9lJIX/S0qM+FFPQtgWXsAEH50mPCX8HZda+d9N6TlcOmLY7MXcRCQwyuRwOrVnlhyUxs7ditbMBF4WLltX1xtel2azx/ZLnOzR5briZD0OSeL9EQUGbnZBV6/H02DOh21ROqxEoE0qAPvz60rMyltbqtdSgHvIbf0qenIulX8JkNqixTDEuAjPmFaSsz5Ywfhy7HWhTjL76e8wjvkzTXQRVRtx7WvbNPeVbqKRRePQ6sYcHiHkgU8S9HbP80fSwLkG+QPUQiuHh/U1duQMGYV7hW0riV98+HJ+MWcii/KI=
    SECRET_KEY: AgCt0qFESWs+EcN+/7nNUSpwZ4snxbG1no7WXdiV76ImCiSCFfFDLbN1Bc0eH/X7EmTlHcnPpVT6YucPN4I08vcn/mqEqNEPJ58uM7Mm3HuXfQxf5fDK3rFTKQuwbTxLDsuQvCTGMFifR999XObIvHlA7ES3x65Q7jYiDQ8FUCQ0fAtIf8eTh1oz3sksYzzxws2y0U+LhdcJs/BYccD+PkeMdumT2ixdCMY1hThz+sgusM+vpQ6djoCg5dZhX/uox6JNIuFIIZvyxrzxmVVuxpeFNYe5JHZxzToDx4CHik4O4sG/8khwAHFH5oDixliwyMIv/CqEctPJb6JPMKbw/2YjjxY/feT6hMs6ZedGTx9gcSVePVsTnsyverPSn0fExsPlEmmPtM1T3uLmm5Z1CSO/c1OqFWsWOUl6veGYWjW5mn9FEMFym8mpQbi3yBXsDrhhoADCWVcL+v2BUw7XsCTvf+q0JFQHsmbKKsPp80mKCLEfyV1UvpRtCJJE5X+JDekcGehbbZi+yuvupLXrH3jnmQpY1JNBBr9qjMrhJYnEDHGJBS6eyzRgQ+Ri6m9gfnIHD5W2ij3GfSgApZ2iJayR3BwBIDzkXvrICkpiFftSZTCS3i/3yUInIJdBivZdK53aLrB6Uq8t4+Lo1C2hKT9cJkzaKhP8fM4XcJQPZDR/TuD8okH/H3DDDfC+WNzm20nFRZCj3mBGWFHEgj9RtE0LqaZcVIdiS8J/zLQiy5DScHsKHpnTiXHZ83THHVtDCXjWlA==
  template:
    metadata:
      name: openproduct
      namespace: publicground
    type: Opaque
