---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openproduct
  namespace: publicground
spec:
  encryptedData:
    DJANGO_SUPERUSER_PASSWORD: AgABDsSaY89nDI/jZs99kH0NZctzH3xnOduvCGw838UGn2M1580XpjFMwBjer2IinAzhLWIU/Ng+8NUudXwWiv1kABmmjZD8iKqKIfJRe3wPUjgTSaCl6PsBw3CMlFgvxtxl5YAORAmSkDQe7QZ33EHxSxqSAMhIdcn+smeYNvmakHY3BhO/dti4PStni+768DQxhwVBpjJhsrKQdP6H/NMzW8JODXcubENlBM4sFTK5kxkhOXDC39hh5oojF5T9i97UEtDqc8A+g/ZPfBpqOreTQY4ytAGX9o5k08cCQmrZyvPYIfGfQ/rHqRbuwkIAFWe1YQjIFevQfYvLwRytZqFzjVgnlKpDgPvpZiCpE1xsEG7kqmxZZeMtppfWIUceAkNjzaDYbuT8mkQe+cB+gPxDXL9olPia1WUaOoert5+JWfkk8CHT8YWmdLNA9B2BHOeKmXnih8BRzWpPWgwIHpsXR24jp57DuKIfDa9ke0RpoqEdBeKcnBAtWA1LUdlFZ2rgPTwYB113YiyKjNvqCfr/MZ4PgbMb+Fjo6eMo9zF/kTtw8L2yg4Mx6AWTws9OiucKEGV41WX1CSAFoauGagn578w3FTMfXqxqZbFUui4dJCp0CycCLM46H+dYwyWyZFXmkoxyR9Uud5xS6BWAXdsAF2P1dwrenWXzfg4zZFPG8Y5ramBEg8FYb7Sp5w0jfyv6NmzECZsXbL5tRhpxpI1+H0ztLN8f+58=
    SECRET_KEY: AgBTd5nFsQREkwRBZzx6JRJ5XDXqTjOY8SFoFQwRPhi/pSI0PMQ7S7/uuTAZ815915xMJwJ4GpSBkPRLifz8yc1nnrmNZP9tgaGtcsbcJ5UcajhEPLmKhiHA1d25sYs6Hh2shsBZH2zozMWS2blW2nSG7UlxEVJqGUBNFcBsbFuMUi1nPX3jwnvRoubhKZmO9qe4Y0uu+A02hmp4z/1/IF8IEKTLfJRHr6cJFjkNWFZysXrJ57UFjhtMeUpm2hWUtm55ZkMVvLLD1rE1m3CXLJ1KSQ7a65o7X89u3en4KTOfEfFJ83/4GWdSB+mxz4nsmXiAftecDvqoh1og0Zbr2VtLs//lM0vgvn6JIMdh4v/NfygOnKlK7VKMrmsEKH5vpIMbt7XVVpkpJJUScJl+J20lZcYwK+XiM9mvPA8Woou0e5xVKmbADNZcT4yfni5ad+2CiPcyX6JUhARoLDQT1LRVKpGbg9/Jy7DPGlQdpk0iJsk7WVQGCHG6kAmMovSVJ0/fRTnDXqIBmQ2Thy0xdn7Z4G0lAbZcF6wio896diIa2JcBLZm8gUbwhszEnN+Vl7tXwMIfrrGvK+Bw1YKypuUuMGHX+4jkF4KHxovvqNYCXoPe6SD43qBgF07irFIyyE0lGod0YLrrqQO7RVoFArRBekRlZaWV8LDwsDRMjuWIBgq4NrJ5sHbLjmS9i4kBZXgC93BauXwWm1URJacRC8ogHtquHYFWSdhASnfXj5YPFPKE1wBeadvceXGtPcn4LLkHJg==
  template:
    metadata:
      name: openproduct
      namespace: publicground
    type: Opaque
