apiVersion: v1
kind: ConfigMap
metadata:
  name: openzaak-authorization-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  auth.json: |-
    [
      {
        "model": "authorizations.autorisatie",
        "fields": {
          "applicatie": [
            "c975302f-3100-438c-96d1-e00c79ef0bb0"
          ],
          "component": "nrc",
          "scopes": [
            "notificaties.publiceren"
          ],
          "zaaktype": "",
          "informatieobjecttype": "",
          "besluittype": "",
          "max_vertrouwelijkheidaanduiding": ""
        }
      },
      {
        "model": "autorisaties.catalogusautorisatie",
        "fields": {
          "applicatie": [
            "c975302f-3100-438c-96d1-e00c79ef0bb0"
          ],
          "catalogus": [
            "335efcdd-8fc3-4114-bf76-3789b3407591"
          ],
          "component": "zrc",
          "scopes": [
            "zaken.lezen"
          ],
          "max_vertrouwelijkheidaanduiding": "vertrouwelijk"
        }
      }
    ]
