apiVersion: batch/v1
kind: Job
metadata:
  name: openzaak-autorisaties-sync
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: sync-job
          image: python:3.11-slim
          command: ["sh", "-c"]
          args:
            - |
              pip install --no-cache-dir -r /scripts/requirements.txt
              python /scripts/set-permissions.py
          env:
            - name: OPENZAAK_URL
              value: "http://openzaak.wigo4it.nl"
            - name: OPENZAAK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: openzaak-config-secrets
                  key: opennotificaties_api_secret
            # - name: CONFIG_DIR
            #   value: "/config"
          volumeMounts:
            - name: scripts-vol
              mountPath: /scripts
            - name: config-vol
              mountPath: /scripts/config
      volumes:
        - name: scripts-vol
          configMap:
            name: openzaak-autorisaties-script
        - name: config-vol
          configMap:
            name: openzaak-autorisaties-json-files