apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openzaak-config-sealed.yaml
  - openzaak-sealed.yaml
  - cnpg.yaml
  - redis.yaml
  - job.yaml
  - httproute.yaml

patches:
  - target:
      kind: Job
      name: openzaak-config
    patch: |-
      - op: add
        path: /metadata/annotations/helm.sh~1hook
        value: "post-install,post-upgrade"
      - op: add
        path: /metadata/annotations/helm.sh~1hook-delete-policy
        value: "before-hook-creation"

configMapGenerator:
  - name: openzaak-autorisaties-script
    files:
      - permissies/set-permissions.py
      - permissies/requirements.txt
  - name: openzaak-autorisaties-json-files
    files:
      - permissies/config/open-product.json
    options:
      disableNameSuffixHash: true
