apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - job.yaml

# patches:
#   - path: patches/platform-services-root.yaml
#   - path: patches/httproute.yaml

# helmCharts:
#   - name: argo-cd
#     version: 10.9.0
#     repo: https://argoproj.github.io/argo-helm
#     releaseName: argocd
#     namespace: argocd
#     valuesFile: values-dev.yaml
