---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openzaak
  namespace: publicground
spec:
  encryptedData:
    DJANGO_SUPERUSER_PASSWORD: AgADLGQSjoeGs9jKGgDppyHsntKINps3TN2jNuXX4HoVcv37vQ9cr3x26NSmABmNe6AA52c9RBsGdNGL9M7KBvsBI3ZRAZI15SseMGQvJkRbmw5LwcFpbthQ23AiyaDVbMWEWiCCNsQL650mUK++F911jRfn5fx9MZ0MdDEwJ/+ixoolr5YJuTf4sV7pwPQmbpOgNRt1ozmu1Hvdr0W5TiPgYY73+KCUjseJDXdlc985AgG8+4OYrCeATxEvmLvaQxPIWqUONiMd00TDzlYcbzIH+2d8CEOO/8q655soSAaRLPEck7URYKEmY+8TVVWMCTFI9Ix4L7uZrgprjVjUz0EE33kpYHeJwjamjvo91hIwWXgYrJ2YwzW8GlXwGjKfWzW2F2vC43xWrGgkSuNZNvRhFMEnfUhveLptXKi5wpau2tcDANkLqTlnUYDp/V9ihl1r8mLkTMYXPd7Av+k/PIYXH357QLboVE1cg6B9SApAIlifL3coI7NqXlVSkIMwO+EOuaPDJ9bNCs2LVyhHh3VQ/MazFZrvV3Kfb5fZ8H8F2gAqUtNVhHFRAalHx8kAHvILIJv2bVTpifGHNA5ctUw0aqKLZJjUNTN6P4v4qlQkLFCvvrBVmXwTsXJdv++71xTaT/X+CjZgtFs97Tber/NA4hahjxnr6PTu6dmrEclo5M3JSeHdL01fkhK+EK9xygcY8mg9qXSayQ==
    SECRET_KEY: AgCaXB/GC7RANPuPUej4f/04ANWkUXA4ujGcmJuKB1js/3A3XGlZ/3jNJAi2HSJnbiA5LTabEAnu+fJTge9jjM/mbrHoEzbcC31dv/9UdK7BzL8mm6z6eTC2cbqEauY4oOIQHjLWSCNAIJzfmB8mumHWSdY+vlpMKGN88OFghvk19+0+LW9bJMsDBtX5f8idp/eUm4AbNdHW7Av0GIF0mW37JnWWIFmKgjf/IQbd8cAGibMrDHU0Sir75cPfGiQTFYYjo06Xfd/bDf5KtRx3ELIpJZ6NON68EkRbSz+NgfOvgA6H4lDmcbzQ9hK/t6xPvJ6UJ7pakVBgtrQpIuD01siZOREyWqF3YSShgzarOjZBf6vIDVmgRV1L8pTd0JfGRjJwwiRNfhgM6ypNO2sA+pW4Uo0nMawgzTfYh0YZH9XicqNNbn4QGw4T96HSA7AQPVizG6AUowL4Yel5LHjvT6C2b8lvw1Ap+aUVspHxmqBqq7R9QuH7nG1es+xNT3VKDR8Xg9a6GtV6sdDNfRQplOZrzL10cYo6AsGTg3BZC9Q34GWiQe+dfGPQdf0fygWDQwZFjJf46/opF/jP4o6WOVDnq1KirmxuM6LR1isGPtdqHoEiWBbLOkp9qXy7Co2pqZyhrs9xlWsH/j3GSe4jmf48amD7FHZPQYr9xVG5PvhkR1IbZXvgA05xINnfZQ9DRJiBRT6WSd3t9Ya0R/UBEXp/LbmCSW9l8+PZoayaJH/4mYMI3gz+HunGqu3AfcsADnjZvw==
  template:
    metadata:
      name: openzaak
      namespace: publicground
    type: Opaque
