---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openzaak
  namespace: publicground
spec:
  encryptedData:
    SECRET_KEY: AgApWQxefFZ+z2uNXNDogWNESfiL34KWjjxJgmeCYV+4P+vnb1BtRJmGqadHSF3VLOxq/WC01EDbr6Tyn/ene/2LkbPelDEOEz12ckK7kXWVkz2Ke7EoqYcRIPjIVwfB1tzbsl32V4nJHL/RSdUp3tHVxd+S1gL4XKdzbkoN0UiyO6VYpj7yF2SzhHqaQiNyjBgkbF73rlQDEIbLhjeYvFhT9pjljxYDlTLqFxNtG7GSx+lvHU650tN+1yP416/soVRF34V1fvxsTMBwwIfZw5THAcyho2veZ1zbk+/+t2Z3Ixc2V/jyb9zgQTBmRiErnm5ZCi+h2PfR6Xd7EW43RVrkK2JOqGhaTeJVCXNEcRM9At2QW13ePjMXyoM+2ZgH/5r6jR/4KNjLO/J9a0xZRLKrAEha+ETouArF9X445E57c302c932AUtEOuwHzWPXOEGIOY5epffKBUmtKMGF4bw68uRukkrH0K/4fIuoW6g6ZBVy4HRGCOsNJeHZgjE3oghm9kMUkM6zMt8zJKE1cjPevd8uBB6n2peS/nHuS56V6RgGzZirL/UYhtqB5osIrKQjX7tTeHmsdCyTlbuXEhRWvfhx652s23ZzMcy6B1UjMDm2IccRHO2CNOnnKBFjo+YHUheGgXO3yhVdyUVwWxv0uaoCvJ+QH1LgAWtYgC0DCzqi3+GGOOo7q7A7l3KvSPnhmsjm061xwcF8p2DojSINizttkSF40T/IUdEpZMMx5+tIwUNHZfl5f8a2YEIHvM7OKg==
  template:
    metadata:
      name: openzaak
      namespace: publicground
    type: Opaque
