---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openzaak-config-secrets
  namespace: publicground
spec:
  encryptedData:
    OZ_APP_GZAC_SECRET: AgAV3gW8gVxhrWanJgSsHSTL3Mxl0q/QkUe3WOJXvG0/Cdfw1GS4XcDFAn5hQcfpnGl/HUVKIbUFTRS2XLO7EJsE+e+oRltaAl/+gG+nM5kriSV9Ji7E002c7Lrz5StGwsWB75DuAB9yM7dcROo6yK85mWcorEFgXA1jrI99s25p9Q90t2enZCNRbKLKvi1E8F0sHErMYKYj9lBCtGgLQSGiefYFYFm8o0gY0ffIaLFsK3wz6IGpzhgkQe4XVQS6JBZ1/ylbBJb5bH7XZ/IDrnZXouvQy9tljTBafn1flwKrQxHyPnZGgUiAhnOzbeElM6DUyfsMdD23Eq6YkQJqGYdlGWsax8yLQwS6gU2QPdzBoh+GlTuEgplxdLfX3DvpZpxep7I1j1b6yb0QxfhvBGPpUeiuS53bJ4hR6KJGcg2hRaR+i5uRddPLxvdYl1CNYMXswcstsAcI4CkeaVfnSb1tKeccNnwyz7msBkVzPmZCZxiITUdgkzkCFcCbLaGS+FcgHuai7khmDN7k/nENg7Ynsvbd3itrcZRSGUSrOw1VJgIytI01nstApgS214o3e0vU5HdhF2gGb7ARRZUg5jK/JjpzZ571BJQEHzcHxNYp1m9ymJeUOgAPPoPxZqwGxQdcMrBb5+gzTjQvLfmJ2uJNOx6PwjmBIjUhhI6nktnoxTVkri8j27u9clOuI8TeAgTVNPSmppNigkrWjggDZEh8BdrT5cDKivumRW72bvOPZ3FSHRDVmDmm
  template:
    metadata:
      name: openzaak-config-secrets
      namespace: publicground
    type: Opaque
