---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openzaak
  namespace: publicground
spec:
  encryptedData:
    OZ_APP_GZAC_SECRET: AgAkg5wOZrIOD9ZWmHKExVqCgNfgHo+ch3h6feA/xMdRvEGbRIlVPT6Q36jgd9kkA0TVVMp4ivsERS7rhGoPuuNhQtRSM791vnfeGyPSzMuY43vWlNfBSiYw684QFq5np8jkSgkMzKQu8G5tb1ZFiHNQs3naTXbKCuG2zUcd160HTELVhISapiz1Q5Uq2HAB0pOUDLQg8/1EYgTyfQpGZwHy/JH4YvpxzJKgu1uoLbqyVfiMam0NbDyMVqQ7U7AfopW0MCCws3PL/gn+LVfkhJrv0aVkNiulHNhscIilLDu3oFYKKWrKxsBV5w7THpZB5lajy+7nOakGm2F4UrmngXZtobimkoZglc48f3lrzMES5/i/TUhOs4KGNDTGYAlcCq0blzJnH3+tNpOKplJqZvfHsz+WF6ruUqunKeSj4UmYzADbKgRYeZFgtheMJHk/UiJoVZyFFgnVS/DwmzILDgiYXPl1zEnmAa8ZRsAi9zqUbbefdSDeZ6FDpNZMlh0T7Pew9AaA6KIuVE07SXi63kihjE0vZd6N8N65swp3NMPfNkAtoNOMGjnDQLvqVXq/xRKOKpG7/pCdTbenJ2+n7QI+HHgE1NcBW/t8akz7LVIL6JgMQMPkXyg/gWqQbzKjgCx3iWknzJEJb8n5frzu+WZz/Ccx7kZALl+X270KnyE8S7Q1+wTpUDlTGYd0hI0WUqlsKIofFHiFFjMNJtmYakMyp8LAq5M1PXMQI+mTvBJv8GUlDtdEZLtu
  template:
    metadata:
      name: openzaak
      namespace: publicground
    type: Opaque
