apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak

resources:
  - ../../base
  - keycloak-realm-secrets-sealed.yaml
  - realm-import.yaml

patches:
  - path: patches/keycloak-instance.yaml
  - path: patches/httproute.yaml
