apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: openformulieren-pg-cluster
  namespace: publicground
spec:
  instances: 1
  imageName: "acr655.azurecr.io/ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie"
  storage:
    size: "1Gi"
    storageClass: managed-csi-retain
  bootstrap:
    initdb:
      database: "openformulieren"
      owner: "openformulieren"
