---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openformulieren
  namespace: publicground
spec:
  encryptedData:
    SECRET_KEY: AgA6PhTN14wLhH42ztE5EDdxauZw1K7xy8lc6DAiGlvK+KwGLRsWEl97dHEkCsN/XChHFijxpLRZeree0eKuQ4o6y2+oI13pN8XXuu6C6OcW7MnTKN38h4Sr9Q+rdJPW1v53R0boK6wI8mUS44DKYT2Cm2r0j/Lv8KGrgzZQq/NXkABIGqnnlNGZ+cddFHTJ6Pplho03omBsz57GCgi7ACl17HdNrk7YIjtMTA34yxNx2V/xvrGmNcwUu+KQVNzvKhbP7PPyPr2ppeqGRD0vCQaQVGZghC0/L6+Y5Y3+UtscIqRworG9Hz59bWgceXnnH/f0uxsaGt2qV+8XpwaOrfiHngaeshRSQITdP+aI+ueftAciP3jq5kqLcUuDn4S9Xu0fh+ES0qR53nyROizDdGjb235+nuOacn78IdSJERmEfkhVvyzumNaQvbGcrrhKIDpoCgInZPzmyH6bbwTkC8jnxO8uAAeLWwc65iaZ3tLhT+d83rAfpcKQfTK7CY0D10td7WdycreeI+KzcShFjoupsIWciCtN+qufHekJNvzTUkwuvY+Pof6ZR58SwTU9jdTVeVSxejuRO2uW8dDmW6YzCcrMOptGUdDrSjBvql7Mdfb/e7SZqfS2gTi71AAySFBb7bME1AV7QCt4RabSQ96ccQWibN2EkCAxkyytMRQHlLv3me8z3oPDigLjfB7U02q/FBdB4/9WzfsQBGSk2ySIXjIB8Td8RCL1jl6oqSQ1b3wesBxhUnp5ivdMqsywK7OsfA==
  template:
    metadata:
      name: openformulieren
      namespace: publicground
    type: Opaque
