config:
  envoyGateway:
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    logging:
      level:
        default: info
    provider:
      type: Kubernetes

deployment:
  pod:
    labels:
      app.kubernetes.io/component: gateway
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/name: envoy-gateway
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
