---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openarchiefbeheer
  namespace: publicground
spec:
  encryptedData:
    DJANGO_SUPERUSER_PASSWORD: AgBmTvX6bW1V8EgHkYPH2geneThFnutJuGCD3amH/Rll3H+DzN+Ie8IEt8p1cfFS63GcGjmJ64h6II+4BTwR2kcPsmgtGIeXP1jpf5L8sUlqGk+nixDVrZPd2bc4m+E0sMQ412ITeo2cITYuQW0Iw2zwnn8CYSaA7o3b8fe7uOhsIP8oZ7yZB2ODtUHZhy56F7eQLMOdRoL85JlJQ0z/lwgTAGlwuuu6cQxyAxGFG9ZhbbyNfTY0PgOPDt1ADnmefY1DGYjJymKSHiM4w2bsQrnlzeQBzj/bxSOGvrVBzpqujb+9lsozq4A5cKl9QfkrEq8nV86mXr+AYrg9Iuysw9cJSF8RT+cOJZvNuZMAQcu5IpQiAYGMOdU9AVasNKWVzsL5YdAPqi9toNjU4ezFr9GmwHkXFRCSIeWGxzP2Tgld2fRuQRFxlL9PE8m4YnLiWDkAreVhSnaGnGODSJcJOYpxGqZ2jxg6PwYNyvEyBUubnvrT4IGpCidmsTKxaYEgYn4cQH5Ko28KSyJq26e35KRwQELb5bIft2YBflP0E4TdKh+u4HCsATjPvreqTy5NgWfw9PzuFAJpcpQPG3nykiEanaRvBF7PTEnkSWFImOI4Hus12l2uL3FqPEQ65+ed+xgsBbPif/nTVn5+5M9a/OVfl341PoQJ4KKF3LYkO1MHMZpv5uIUM7TWl9aTyGj/pr82fwH03WLgJQ==
    SECRET_KEY: AgDDblM6fxyZEd3WZrIYisuJBRS2kZ27Rtaxxa+EvO3mr8j1FJNk1rTsaFUUB+ZXesBQTYBXHEiFCnCpS/hMkYhkGGNycRV+MusT7mWqXlJhgyoEOC1YQSweMsPvC7DSzu4zk5QGQXJrnlOAtslzv+nEoBKvb4mzZV7O7ZbE6fcilLe3/tURaBxEiho9+n8/i9NkYd85058PLbDpXeQuEkIkGRniZ5j4iCuoh7qqof7OHI+5GZ+NDcjHXgYJZVexoFJ8k4eP7hTG3zhC2TrwL8AkGliR/RlpEZObB6WA0VFrul4VUuB7r58zfh34/xarK42axiFuL9yVwEqJgsuW8bhcJ6ekIzzNpUOjGzAaa2MO8CPgvA9TlP/kjId4mdFpe627bv4EXfzSDv2Of+kx5BWBmIktLEEGcitZG7JRBIur9AeeR7r/x4vDsYGPlHt3KfVx3n3/FI7to8c/97UySb96pTPg/Msx94mKaprDZbOkaQxoj25R3LayJm05l1PkKDz+oj/KupoSQneYyBLmwVY1c8Zhglu7sPFeTYWpgsOCdPqaN4TFFZRRSRO7HOyffqU8W2lqwETDWnhp+iZ4FyjY9BRIGbzrLLH9lC6HalwdYwtbT1EaHudgYgGBKyrCxjCZ6UO3G0rb8YI3IdI0g4kAKvhcPzmD+WT61gevbYTRnkW+Q1cUUubsFOe7sng9yVY8vKtys/2i1TZErAgIZSb3aABwL/DkfyE65/65hGhrrchOAfqdQgR3WOjjJcixShzFMg==
  template:
    metadata:
      name: openarchiefbeheer
      namespace: publicground
    type: Opaque
