---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openklant-config-secrets
  namespace: publicground
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    KEYCLOAK_CLIENT_SECRET: AgDWrasr9VQ0XNCnx5Pjnn95AGuTVBE0WCLBBkFHM9cUsxVCThcox0XV+6kki3A8CiPJ4ZK/+JhGyLCcjirweETPrbh9QJPXIq4dbqzz8Pb2+QQR7vdyqRL7yriNwJ3TIp2xt+6JML8+i8MSUv/pmakADaAuSHmC53Dbgq/nLZIE2ZiqFhiAzm4JlgUZgoYaTEr3nlzKQVd9jePKOk4HdjIaI3+93wWbKKhJMbaQRzhMhEQnqX2i6ndwqAA+EfNY0efnTvn3WztcELF3C5zhlG5NeG00Z2KP5xSKuBb7NVGbXIQzYKiJB4Uft2o+qt37KxjUKtbIb+gkqYxhvlkVEeunP23Fa+3AuerBrSwuI1rUfCr3gbf2TqC494xFTYn24xeLWm7xTTsQcmUVQ6wlPFopySEMBvGsXBUpVLHQRVvO5Y+94OGJs1By9sJuX9hCTTkRn6o10mrbyzm4mqFbTfEOJ4z33Ud0cShD5hMjqj30S3ZywmmoOS5a/7Xe73hLU4oZ0eT1hU1czXOIpTLPHFYzMn5eWp3YspFFImhpFZlNpRhZ2dd7w2aoBgNcnVUL4zVXggNcOeJAGknXf1YBqzKqUdiDwMML6S7srkswIQp/y12x+ggZ+aRNSiCnmkoNWmH8FZ24rgkDcGecoG+mJUAfkN2QtLT+F8BiFRuHYHIImEmUQyQVUtzmFK5UZx0khLM4TAZvx+ZA9na22AKUrqyTyaKTZe+DQrvC
  template:
    metadata:
      name: openklant-config-secrets
      namespace: publicground
    type: Opaque
