---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openklant
  namespace: publicground
spec:
  encryptedData:
    DJANGO_SUPERUSER_PASSWORD: AgBOaFXbX3K9mJQppm6bjZ+Xs8h53mJlVwgZ83TieShnwtaCfWAzn4U4ftR/cIdB29qIEYww8eiq9dY9OjK+jEQEJ4nZU6CRu8nmXAdXshk746Y3ydfJSJaEzz5kn5DbXgezqBv9LTY+WwjZHK1oNLA20P3rel7Kt84qU38+L6qxy4egOEEyunAma9dhX/dT4gPi/NBx5r7XN400BW9CoSoxqeUzSLGmdgInl/SVZgWtdWT+xZ5gSlPlzudY6/tA2/diIzwALcDsE8AzQem3N307LTgL8OmnHr4oaB2tJOF/WGimVAjjQi2Ch7MTSka1PAmunsQu9XCv/awGzIHRUCGQ8SFVOUaG5kuCCMUmzYbq9FcbKajLO+O2oqV97hG5Sl0sx1ad7ZF71kzP6+BeFfUeK1AAHxSecssAjB+9KwVD+9fbIeilzU5pJu8jDzRNDca4B5rdGI4AvpBlRIsFTMp9ICl1/I36DZ/AhBejqHLExALTGsHsTWixbeIGqCghgsp8ofduMCNpmTubyb0rctJuEH9t9X7dgd8qEdv0l8N8P4NwzTDndeSb2DhKeIQh8R4+S840rFCTb2c0e1dpJx8xLLtWi3Y2RUp8vBR4ve240eoaC+HOPgHYKWBwmLB0HhJJygyn6Q2QetYgNH2UBu0VY4dyU/NruaO+/lirbSbdi80MDLYwcUQLmrJxBfGq9eua5ZnofXyz0A==
    SECRET_KEY: AgCmTAVqE+1tbVFsHiEhRR9EKRV9chFSbx9e+fxnoPW95+wju+4I4iFjz4GljvygnmM9i0Fq7jLs4Eom+NzLCoZggUfnJe/WrtEiqpQzGkbsqbsE2ZMH/Z+ANaZToAyYdWrt03ENkE66bK+EBGKhw8SUO72xEJa/Gs71+fN2kji3ZTs3SvuNnv8fYNjjBjncyfXFgGGYLObu+tbbu5d/KBczxtg8Ji27VudQ1e4gSmO2f10eJXVGzVECFa6L6lMBY94pyWkbad3Lbn7+mzhUnoWhHGhae9sK0uzgBETE7lCss+YVNs8DNeGKLD5zIJT+7XMHyBIafYcUczM+sDVC9xG8my1HJXKQeRi9keDOEJTdWNAJ9z5Odr6i1qjH6lGB0ZqnsVY8Mq9M480RQ1+DSQb7PNH8huzoc0gjs0+AfA17K2rMvKuDijwYX3pSnK9QyaWVkW6td83fZAizZ8HOALX66dMIR+6yZ8wGmmcf0xTpoAHkH7uJOrxQi4TC+d6IfnVY8Wz/axtNByhgQa6yrK18r9tr6l2v5XH+fw9oWOXFYV2GUOZZ9AylzYJysedh55komK+UGvK75EMYhOk06CcHb6zLpPucWe3MUJ0OWRnJVWtEkTcUxEy817Jx9n1Fxgn5DmsKuLA25N6mu5YIdCT3C9ik7bcbEcvDVgdtQcPoq3n8/Ws6gg7hea2JAgvtvoF54oBk/fwJYCQR8yDXfElnkOPXLQHrdo6Bhx4FeJWXWckZwn9Nigdkyyns/VMCAGypPg==
  template:
    metadata:
      name: openklant
      namespace: publicground
    type: Opaque
