apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Vertel Kustomize om de Helm chart te renderen
helmCharts:
  - name: gateway-helm
    repo: registry-1.docker.io/envoyproxy
    version: v1.7.1
    releaseName: eg
    namespace: envoy-gateway-system
    valuesFile: values.local.yaml
    includeCRDs: false # We laten ze niet renderen, maar filteren ze daarna

# # DIT IS HET FILTER: Verwijder alles van het type CustomResourceDefinition
# # dat behoort tot de Gateway API groep.
# patches:
#   - patch: |
#       $patch: delete
#       apiVersion: apiextensions.k8s.io/v1
#       kind: CustomResourceDefinition
#       metadata:
#         name: gateways.gateway.networking.k8s.io
#     target:
#       group: apiextensions.k8s.io
#       kind: CustomResourceDefinition
#       name: ".*gateway.networking.k8s.io" # Regex om alle Gateway CRDs te pakken