---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openobjecten
  namespace: publicground
spec:
  encryptedData:
    OBJECTS_SUPERUSER_PASSWORD: AgBvIW5NhWanJ3hbdk9Kx8Bh6k8TJxXqrr05r8br7F592rewbYMMmhwLUGkWTwiGP+5otfUf/htyxLtqvUwDFGYxvdsY1/6YmsMNJcqlXnPXUpmzroVyBfuQqLRMZuQ2X43PqXaPWm5E3XT8Gs2KvabYLamcs5itcXo0DBRJV4eeRQcqn4cUMmAdSKdhoweiMTCOfIg0mpQYtWh0vZ+hCFXf3jFpdtwz2O04sW7ugjzF4ykzJ0HE7c2t+WzGmRmjWxUWz7mU0DQTQXzp/Yefnbo2e9NU9wZIPmwNtBYsdxCIT6oIMITH7ypg4iwXyJXMlqJRIiGAqu181N0auCMfgtKrCcSBtMRT8suy7NeEyVo6F0Kn8QCqRFO1nllITlaNCnEpFUzIKXga+uEFZCmLySZyiza7w4jqZ0sUVZ9ftvWF5QXNMQK8s4XCRAJnQTK18T8sPRIh30P6dR6j05xYVyUHqavb1gp31DonMupvWgeXBoFoXFHYQ7KQtroU5pj8YO/cPUZpx8oNAY/jwpQ14aIA/LCp1dua9xM8j4xFIaUsj+hPwYSS5rxQAnNkkxi/tuCAKldfpQPg72je4Uq4rOnadGW5YHCoh/cvBAM5vVApfoH7cB0gkA7CSVKMM6YMcwMMuPz6K3yonmqLO43XrFgx7CQYZ0M78c9qKyMduJyn1SIi1xAx1iTMpKScugZE7/Av02GLzOWUWBCJl3+I5hj2r1k1gUGBVPw=
    SECRET_KEY: AgCE9LUEf71zC+NZcJ5XOn8nqNtacxSYcqtIohOkOHSe3Ek5knLg8f9j4yDH84BK9MSUjtYAftI4zrBEFIfUZ28gdtZjdeGOdJBYTsRAbIzSpspKWFk5fpzQJIa93QFKKOGFuYeBQG+V8G/IoJbfg/W4seaxKK2v86rhXpVLX0vBcdbIX5oEviuNjka2aPewqm1nDW1lnJsdN5UfcZ6gFX72lcZY5zdY+u72y928Ow3wItpH5VNk3splWw/CX+v6oQBBWBA0uclkfavDKHEk2sVFktIuGE4Se+Y0U/KBcGh4Fjq+82PxqEN1/ow3R4hg+cMqC9MHTvDoezZTC4pKVHXKOlXj11c8pp3LQ0J2flXy17mUhwBE2n8848ndx1oegU+C9nyH41LMPhShywsKsMcd6XQf4yuAYaCbaK1mf2muuflsaUwxANDLEQycuY9rgV+tG4kq5nimhAzZEwriVV9fqEgtxmRP+AXaT2aXgLlF77L9gJZpmUUegKGo0sm9bzwcrVKjwDRVGAytq7Z5UsJUKh6G4ZctDCpbvIhTNEtWRASLvKO0dBlx+MmFWow9HMms2d9s91KvTsQ0889IIn2D8Qvg50+hO3h+SLFcrTimbjgjq+UpXtnIsUisjg0b+JpX1c9HOiTC2jou/KmLJyMyvte5LqesEmt6vSkcdD26qu8gBnQFlYzxMpyADw3DU9umzWw1NYh9eWUww3qJruQM73uOSfN0oN8+vBawYBTgOYCcei5Dl6OxpbqZQ0tyFNJcrw==
  template:
    metadata:
      name: openobjecten
      namespace: publicground
