---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: objecttypen
  namespace: publicground
spec:
  encryptedData:
    OBJECTS_SUPERUSER_PASSWORD: AgAWdyT2PwpQ3bojD1fH60Zq1vPPXPc5np9AC8DwzFvXgyECu1tSOKC10UBC8atqQInK0tT2XiUbOP2t/UwAh5KmVZ24zkXxDEL57IQDjBd5buqxDpifKEuysH/MPBdRTH2kcJnm7QGQpv2LWmI9+Q3aED6DLszo/h1bwsepJOtC+/4r9HJykyy0gWtkJJQ15ijgoRhO2waHsSX6SRwpX3WkVexRdL+IMln5ApVV5Lh39uCB/Tzxqy5y2fry6gEHEcYAkRe3UFZr9HBwAE0e6/qilZtdAiU5lZtFMtggKsPW8UaKpQDTrcfRo6UUgkPZCMKrHnBbOouk2AfUbWPHEI8zSFT79QBGh3owxRpDdT1t8wyr45tKEFi/U1CCL5DNocSP5c/S6jBk8XNKJYVFy5+anbiPxxYf93oLc/K4H5sxgvR6H+N73eTXAFoVGncM0xts2RkHA4GwNmYhBqJVIz0pAOaPRTUJPPHGvu20NY/OLY6ZHHcdTLlVuWbCfSfCw/JsxEAUb01oOwzgFVqdg5FIwHQFboh1vBrV5YdCYFeRvhXPUf3a5sW4p6jVh/a/I7xRCT5SHZqjHJ0JrN31zdjdgKsXl3NZq0qbp0MZ2cQ0f7JHZTemx9xhzwxoWZffJWko0n/lOc2w9iFZRUBLeNcgCWevPGVeV4eBFaTBNWBDV1g9eIi5ud4AE1hyTAOkkX3ey3FOzoQ0DIO+6oNRAkgP7pKyT+/WUZU=
    SECRET_KEY: AgAMB2vG2+uZtGMpsirrw+AYFt8QIDfpJFzthpLBxWDOoEcUWNpK80ATbw9BfbGTzFlEkF//3aQwDqzSsEL03roy9Sy1t9WMR/zwsQnC6BksKGF3EB8Eg2+wJcEGIB92oizPNH37PVA5eYkemDRmVkvJnlbxThZud/OxbenuEeDVDVXe7a0DjlDsFMSPrJ3dw7zvGhgyArdqLKx6cYhvALksRy8mAFuk4aBAeLp2cve9KXA77zEUL6MYy1TemZPwEgK5UWQDlHsm118wwoGmRuOwqbyYcRjziWbZVNWqIYGzucMSeczDCPCCmdlcRo7z80K8NsYKEuyXynaSH2S/M+0/LPqpAeokuvTmxqBZsJkE/ZP+jwrOQnstNdl29dUohJ6aVHT8isVNAqe9ZAY1J9AcIA0Veu8DGESZZMeCIbWB+cOwtXCwlx2wYg/r75V05SJPL6ei4Yt0YLVYHkPWMvCv/OTc+iQ1/M8xV+K3vJFP6rUJ/WmLnh03MaPt1DDZWXDRHiK+bex/BtWBCCvk0BmmuoIVXWH4n0bROk+HNpTdh9S3NsGnGxzbdH0X1gHCSlO4qTaSbpZVCpNFze4Yb8480EKHrfmxNla2XVAeZG6Lr7AeMbVVuHPUt0zmHCOJvtLOwgIPnhz8uRJwPAjMCmx2evDnP8EvAgz2fa+dxUEs49FGhTeSo5YgLPyxp3kNrpPLRAz3VtTENS8EnaKgTaRWZMZUS/sXRvSa4I6CdxSsMvN6q4Tkr3RlyCpPOEDlklfEMA==
  template:
    metadata:
      name: objecttypen
      namespace: publicground
