chartName: sealed-secrets
chartRepoURL: https://charts.bakito.net
targetNamespace: sealed-secrets-web
clusters:
  local:
    enabled: true
    chartVersion: v3.3.0
    # additionalManifests: "infrastructure/sealed-secrets/additionalmanifests/local/"
  655-dmn-poc:
    enabled: false
    chartVersion: v3.3.0
