image:
  tag: sha-35b82f7
## config values will be used for generating the config.js
config:
  apiUri: http://gzac.localhost/api/
  keycloakClientId: gzac-frontend
  keycloakLogoutRedirectUri: http://gzac.localhost
  keycloakRealm: publicground
  keycloakRedirectUri: http://gzac.localhost/keycloak/callback
  keycloakUrl: http://keycloak.localhost
  whiteListedDomain: http://gzac.localhost
