chartName: keycloak-operator
chartRepoURL: https://gitlab.com/api/v4/projects/50848788/packages/helm/stable
targetNamespace: keycloak
clusters:
  local:
    enabled: true
    chartVersion: 1.0.20260403001450
  655-dmn-poc:
    enabled: true
    chartVersion: 1.0.20260403001450
