---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: referentielijsten
  namespace: publicground
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    DJANGO_SUPERUSER_PASSWORD: AgAJQmsHcJSTCPbjeNoZUbhxcXtowJ+tkKwYsG8vmt0JnBi89mCz+glpxApwLKHB7Kh0rsUZl9woHCs+dkx2Igx3TQ/R8IbGVv/3H0TeSbB44v6Qu3tYztLnudCFi8MMBvCt77JC+cdGLDADdPL+EsblCHY7EuRI84p+r4CyDySETe8nANQ6N831J4ilw6yx6VZUQw/N+TIXroSwKQnNDXbcJ2Myw+9hZQ8V+QXerCW/eOahqr5up5MWqek1gwKOR9daq/XjjC2exCGVu0EcajXRRDgjbPNlNWqe7pX5GZHewcX2RA5+BWdBSwYGXGfmTIZJoqbD0kzJIcAq3sjNUUWDQG/82bZyF6dbAJ1I+j+3d6QYXveAqGFE979N9iHccSofDhmc1HEkOpHcbiQm/pOfTg5FfCz8UB0pKrD9JTv698rQptXVuxk6dX9dOO88Z9ofa4QGUYKVlbHgteL3cnKjfFl2lFWmqZdT0SliRwEkt++11UdoU8aUZJlHFEc+YPGj7kSCPb5m57lEqOq1xWkVNmFwJ8TXJgUHCj3hIrhT8qKtyRNGRKffO781MAYV8Iscl1oZ+vDiPVIH/q3kZRHvLqYyqX+uEMJ+jP13Feu7JmCliuQJxD266E0afckRyNq7+So/x/XNSJHdPtiVgPeb9Si9/6Rt6YOQadX85u3ZYl6e0nEwLhferCWkASw3KiD2ctTREK1/GA==
    SECRET_KEY: AgCPkUofb5TzedMiGDmvtIlbBDCshKCxjy1T51TgbOXMZu7STj5Vgb8OHsx09oM6oyoVTQfN43hon/h8GR3iORqKNKFGoq/uDD5dthZSQNBXuAFuOkgqCEgKg+/ve+nMX4+kOtlS2erUzpOV0/AAgmwkFdRswU/+VCtT1RhcZ/Kib6EPEPqTTYfRTGQ6tqlzs6Cvn6Dh2mWgID36Q8MSSTnHYxz0xZxqPGbUJmkD8vYURuqQFruItyXYKzwWAZryFOVYCfzh5f0a+qWj5Ihbwfynyt3BaXcGo6t68ZByVIYs5GCjCstS0RwCDqWF3G+8dPNpPa5XQ1HjZa8E99J5JNTl9ITwYCRmf2WlVwWpq+dminKyG0idmO3GxHZfeBU/zCkEkLmIGvVJdVkY+sl01fm9pPdn7ENGNCtcREPApqbmJjuvIfbovdekTVOlOguGQbHw/8a7Dwt6t+q3LdAvkFwRttmd/lF9l3xRFkbt/K0Ua2YFn3xqtQGdXRYzL6Pi4IdFKblCVrsX4xWoC01mk/ayOxDfjIUK8fw1hSqiYFk/tytYQpX0kklKXuSTIvTDNzgU383WrSHVjd7u9UpdCGIHQZ3ZkdKOg0U306QNbvRRbPbQij4z6QIJql9jMTAPu/3podVHb2AtlsYWFhk+T611dIRAeK1T4ymfx6Pz3HeZkEc8ySp3946cs7rkCHP0W5PvaUswoCMDFEDFdTZv6G2rKGon8TBTgCbXFfa16IkDwlznL51M9y/2lvQQPMMeXe0XlQ==
  template:
    metadata:
      name: referentielijsten
      namespace: publicground
    type: Opaque
