---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openbeheer
  namespace: publicground
spec:
  encryptedData:
    DJANGO_SUPERUSER_PASSWORD: AgACR9HGTUoMONk05+2/IRYngXvL6YDRxvj7V2WYiO475vULtNgZRwDNR7v7XWBhpStv0VqxI1fb468jmb5kG8buDAxWPCDJRq6c3ab/ePopJWOsGGsOTeiMXGSDtw0YaY0bUHH1vtjAuaFFcPtp6uy5Vdy+KU6uPKQX1FHlQ867i4YN4HoOKv8fLM6acHQbHZOlkiM7sb8xUFq6KuTkGEIVR9iaMxO/uOEemg+iRZKCfThHTMIJ4tRIPAKJdiINfsM8SGjWToArDnY0gIdhzhAvr4MOhmJu1hU5lY8WpgO2svcfcXBnup6HRriExBSXdw2/+YjG0OoC7LJ/NJMtuT5Vt9amRWZu3DQkiP5n2pJ1NZNPwxotz2oj58wHrloPQD1Ih+jHghfpOe68UtlSJcnlL4DbaIWzT5/p9Ih5k43q1kX2A7I1O6WAP/u58d8pM0pH30qr4Xlv+W06qO1lioTFpfnY10eWMgHBS24iKbQwepGdCV7ENhE5tWmYJro/MeHMiOriM/cdYzgalj9cIGbEbJ/2ZF/yo7dJnnlNhTykxOrtqS0TR5tUAOpMpoZzHaaoreTd7a9J0sO5sbzkzNQhM8d7XQDDdsNArP3ax+mFhEjZNZHtb/hwf1N5EPOXZCdGl5TJEIwnMJGz1Q68LkA/oTuXybV2EhMVWcn6n+TSReWp/nR4LCmTobxjXBC3YWIrl/D/T1NApw==
    SECRET_KEY: AgCpfcwiHivSP5XAb+OI+l0C7K+wq8uIEld+9NnLoeXERD+/EFjUzEpJNW6F4OK+Dvg49YNuFSnfnDY+5NXir2672/Cc4PhGSgZiS9hPwaBJww3c+tRU6/aKxkTnkSSl8/1+ytdvIlO7QZ74aMDNDY7DLLxV/Y+cpfzH0T0hPaY2kH55TnnxcWj74gQ/mX+diTOALAy6EUfDqgRg6LcI2IWrepDAmlWYrxldmocxwrl665h8quQm8/QIdP/M/XB47ItTLkWNwlLWAJOjK5QpDFFmkclZIgjUETsSfg42Vy0Lp4XgFwAJunkAwsskkDRk1AyP0bxg2UCuu1SzpAYsen9G9oFl/QG2CvIrs6LBJwDk0PSAvnO9VT0zxvoGDpj9vrO8fiFXlVkwCKpeN9wvywKsVJPB2JUIp6Dh0gA8ABWYxRqRWWnQ17VifIDmLcihLkggz6eFiFkYOyXoXDHDwVipojRCzeXs5VXFPOr70twAeesZ0tvwyt/Lp4Hnv3hdMEnFY8dF7d6rG28zGLcTHWYFIhfS7wEnFqnNR/jcGS2PhHHjsLvcs1i5LME8Y1fWk16kERZHbQJGzqjftQ2fyCAT3TEZh3eiDY1XS6ccKVg693afWNF8itYxF3EuVwSY5pu1l+92G4QNGDB13sgXT3Y4p5T+5ERInqvZvtps7rf1AjPj4FTVWEfC73rVGYP+MbCGYpfzHRlK4veHDzBfy/tN8cFtWdlWslSCdzDq27/TfZurkHKMIxOxRZW9DTzsb6U33A==
  template:
    metadata:
      name: openbeheer
      namespace: publicground
    type: Opaque
