fullnameOverride: sealed-secrets-controller

secretName: "sealed-secrets-key"
keycutofftime: "Tue, 01 Jan 2030 00:00:00 +0000"
keyrenewperiod: "0"
commandArgs:
  - "--key-renew-period=0"
  - "--controller-namespace=sealed-secrets"
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 256Mi
metrics:
  serviceMonitor:
    enabled: false
containerSecurityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
