fullnameOverride: sealed-secrets-controller

secretName: "sealed-secrets-key"
keycutofftime: "Tue, 01 Jan 2030 00:00:00 +0000"
keyrenewperiod: "0"

args:
  - "--key-prefix=sealed-secrets-key"
  - "--key-renew-period=0"
  - "--key-cutoff-time=Tue, 01 Jan 2030 00:00:00 +0000"
  - "--controller-namespace=sealed-secrets"
  # - "--key-renew-period=0"
  # - "--key-cutoff-time=Tue, 01 Jan 2030 00:00:00 +0000"
  # - "--controller-namespace=sealed-secrets"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 256Mi
metrics:
  serviceMonitor:
    enabled: false
containerSecurityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
