apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  ingress:
    enabled: false
  db:
    database: keycloak
    host: keycloak-pg-cluster-rw
    passwordSecret:
      name: keycloak-pg-cluster-app
      key: password
    port: 5432
    usernameSecret:
      name: keycloak-pg-cluster-app
      key: username
    vendor: postgres
  hostname:
    hostname: set-in-overlay
  http:
    httpEnabled: true
  networkPolicy:
    enabled: false
  proxy:
    headers: xforwarded
  unsupported:
    podTemplate:
      spec:
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        containers:
        - name: keycloak
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
