---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: objecttypen
  namespace: publicground
spec:
  encryptedData:
    OBJECTTYPE_SUPERUSER_PASSWORD: AgBzttOvW8fDFHzYEltMIpNVqKWoQ9d1ahrLW5KomHu4FOlOoP8Pwh18zgTL7SBHuBnwczy7zKpQfR0hWDHtNWK2c6534YoVRNn85k38gXxZbhaZS9rw8OSh0PNEJeDBDkgarTt8m12nVQZg881AK5O4DuULjCC+O7q8XCCPaR6+qgDXMeMgGawGuqIjj8ut4doVvn7m3+JgY3PE9vzx3BDQwdgFzAD5pSvJz2EaePpucR/Q9uZ4+M3nsxLrIlefCb+wEeQkICo4zDVQnB5LYCshDkmb8737P37zlSmMHaO0jpzzZoACbuijvxbrFmR6JlXVw8BuC7ov0UFAipYb9olCpFqPKlNlSHgdwmAUGGpYRgeCyQ2u/S2NQRgzaKlYQv9sMsNfpIJhOWUDr7OAxROSXwYw2VhhodlncZZ0O/vJr0wmKWM72lNz7m0VsN1/amlxTpjD2TiIL3XaPoM4ppGYAKlpZDUWYrqNdXcmKXT/D3GgMBM53nrBXGaPjc7SF1cXDcHEqUtIqHnEAUHERPsgLnxyvs7MJOLDJVMzsTpL2BzITChUhSoysbCl5g4YEo/rXRUjxKqar492Ltw5UxkbS/GKGo236M2LtcCdFm/w4DmRRAUvErqZeo85gizu/rVLZxOaT5Kj0EUU3bGbMMQodEH5cEUAAJt98vmrPvMb91Z6xUpZvTH/UDAZ4ajddmzKuSZ1adLZUw==
    SECRET_KEY: AgACo7Yu6+0B+NL1Vhz3qLgbXBOiqPnCPHlhjGyiVIjaP/lgwbUYEizUmBS1t2mh52dDp2dlvkwxSZ34ma8f6Ov4EPq7d6k0zIqEsVgWlMLz+TOW1ekvpONzskD98/ZQL5V6cJoyv+o38qP51dLpyE4qN1X8stljC1USqryT3FZyA1p1yJvBDRoqlhjRjMKikg6U7W8uIzB/U3ImUi1itdlZhGrQ0vh8Pay9ASV3Qkn5MVUrOMg4xgCN8ts4YBcyTa/Lp+3n96ZPguEtqCPysiJSpjeIk7QXVU6fOgz1QpGn9JJXKTnDSOTGUTPciL2Zr9C0DsLPA+a11QjK4QP2x8jBMCUmUnNYN9DMvYPWWxC2RCEtZIlTqRehbKGQaIzIcr2wpdjaeoTqfARddMU4qLe67wNxHXP6zm+Toq2liWAQTppC5X6Tp2jRm941gFNx6teFE7clxUD/zI39CdLyI+m24z6/z0cBmoACqvd0QVyGtsGZ+KxZeG37tZyTDWqOBJwopySsgTUZXB83UsdZpX08wU1V+GYYLKftBWAW0INY1B9nWI+2RzE5Yg8YR5t63vFNbUN4romwNHH/2IvEZ9j/i3gqEp/6uH6ZkctLHCdRybG12uir9OBXI0mSG6fJIU6kjSr7qU4iYdHu98Zu0swKZ7Btj6ZdyPoDJOOMzqZJRj/MHpngoqi5M2Vioy1/6PHLmIo7yV8eAyDfcO88tOkCehCGLZiWUcA8zWUcKdpWSJFzujqnk4gYJ+W4nCtbSwq8ng==
  template:
    metadata:
      name: objecttypen
      namespace: publicground
    type: Opaque
