---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: objecttypen
  namespace: publicground
spec:
  encryptedData:
    OBJECTTYPE_SUPERUSER_PASSWORD: AgDkuUC1KmjLPEMF2dDfjGYyfmJZ5ca44/nJ7KcqM1nQIw6HlCebYNQ01ucQJH0XIjF16ijnDIpPalLI3S8sXAoBvmtT5uEpZv9fvW8BMx0vdJaY/gNF0IEiLkrIiGQ4fGcmq+pY3B0hd/NybTqFRylFVNAwtcbJkkzSPZnJxG4KJzh6mzG9Egt1kPh1a4iZ0dLOeT6b6LtqeMPf/UvjOxdTizCJw9Elxv5phHliovz2OLOi3X9sRYtEH/P/kYgh0Xsc8gialeLeVTzGHv2GpUdtAZpRPS1ItzBzOkydkvwDh9R23VnBDgG/fS9RCpCyxTdv+6e84//7qhBjGHPL8ngWUkcYhVDDRUgRGoyd5T+v7xy2lSZXcnNL+XU14Uwf+yP9EWDuo/ON5/6nQCN0SGC5KK/mZLS4CA9FWHOz/Sbx2dQ0KtVmqT+9LGJctNcwvat58kZNxSoJg0z0pT88vnuT7FU1Rqdw0PONyeNcHdUpJIpHeiaD0b/X4Mzm2mgA+VDyU+McTuFRPRdpupSnbOiP4MNUXgS5jKZ3TYslrB0krZwkEPM+b3bJR3zkYE11d67TpBwASmWta1im0dy8WHPOILMkd/xZN6OSYo07WQWphVY8+3iFqLbqsmP9czNh5mcyj++CZ0wvTOgTLDibC59xPNunbfq/22wan4Kt/yIFLwXdOAKZvq+GMxLClnB9AKUfk5HhsFqJAQ==
    SECRET_KEY: AgDHdsIroLbLXPI2Fn4YxvfHVqyQc+KseuXD2OeP6tVr1/Dyc7+VQo9vx2lccT2/ql38o+uYfvNE/VGV1XRUsOK0BC9pGWCR90psemauFHOzgqXA7JxVcjkPRKJy+L5eMTgQPVRXJTrHrMA2XAtbuTV4j1TLaecMwGSyGBI3KHa1ljGOyBksH6rODvoUpo8Rgz4y7taPfQS2x1ii2nNhoJjXAIcjmn3k4ORDntBpW60c3L710/7ShHnNfgeEaiy1mEOIBJnQi4Q4dAc0Lxbj0eAwZHYjsh47JV/hmzg6iTFkdxJknNdrmTM8/L0JtXRA4nywodyacuPArdo2k7Qfjwng+Wpwua8gdGj3qyyEYgXnhQGdA16AxvRwbgDZ9+EbNda8xq5kKTh2x9dG1RE9qcnQ7oKBqTCV7NurZMBay8JmiN37CwSWew8mInuGFcwr7iya/xR1Oxcyu9CoR9VskQ25RJK/Rv/b6b1KCmDD0pVUyC6yHtXJcvmBh578BNr4OqtS47jSsTvlwbkex3uM++EN9TgBIUtELwQU/lA0S4t3YtVfxJc69mHF10jAupFd4PN90Qry9ylCnPmWaZIniJGj63Wwiy51Hok2wSAKmZAX+BIn/1rGBzawRUhrvJHb1xnnO0Yghl41ohj2271WrF4oc36CAgSuoypkVLcBqRigTYuKJEByqy8BwG9Dh1QI/9rrv+Yu4NDBdKewTls3ut7Ts4gNU+3z7sh18MwKDwH+4k7YareArjjn3lj5TVAVmJlNTg==
  template:
    metadata:
      name: objecttypen
      namespace: publicground
    type: Opaque
