---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: objecttypen
  namespace: publicground
spec:
  encryptedData:
    OBJECTTYPE_SUPERUSER_PASSWORD: AgB7LVWEck36pQRWukhDYMp0Iz5LW1mUxbm8ZdZrjJNL97T/ot6YuFNY49VQVILS58NnnosS1UNnzQKjCDi96Wk2TRZGHGhPpVrsOsBYVFpDQI3YzibLYFdAsjKqvjU49ReNIuKn8R6+s8uunbVmkGcXN0zIQ8zwBrfpX9PF5N3ZGARIi4ByMHUe82sfy8ewNR+t78a6fatMuzf0tQ6GyHZrBs1S5/SpIwoYaACxfZcI8CkVsYnZKqeyAc0DYzV+N/jUc0eZMMLTJiR4/B32dUsQJ20zi7/wuvA574iVzYBcrdNS7oTLGCxnAFRNgfPFEVkXAhW8YF7WwFCSiL/yLHOtpe5IOISkaX7ZcfUyafsvWtBo/oGAPf5UG5sMcv2/HGCrVZi3RcW294IisbW/ndYiP0da/vqiZUDReGwXG/f03oRWNc1qWATciXwxkmP8Cy0EYbTJdGpBehhdaNTLsKZMnC1lcu0vBSpATbh8Eh1F7D4Y1Yc6USew4CbN80dYSsQap4yD9RcTQYcgk0G5Nb42U6+ls8WNw6p9b7tWt1k2q26FV+yCwXDpcGxCoOo0RKvokjkfPge2nM/MzVomM3L9qfag+R0mZkplF/Yhf+n6Xbk3YGAhARyqGJlB+wez9DpI9hM0fjc2aurCQDLPXrvpHA/837/rbybpR3mhcKL/tdgd4uKXWZfEitWoqzRd7c5fvwUpDcI8VA==
    SECRET_KEY: AgCL+ALGm33QsI5231qFyz98wx3Jx4GPL3pc4WlmrAD3kSqBJub8MESM4LUUQhk9NeZMXKtCY8RHNRUBFlNgCpn8t1vYKMGKub9lpANJvGduHq88KsaZoY0kRRjiwiEdiZz9/5cjGIilC5lky6qm5ge0G5zrI16jRQVp3N82rATkjFIlfN38dgAooB3hV0irREFbNtdB0Pdl+1wMPY2hNJWKtBaiAal5XjJi8gRkZtDGOMRLD+5KNcZ8Thqw2MbQBffv01iDKl1mvMkxF39HLzeUR2ntER98a8hy9J5v33A3w9RQdiwcySDCLyno61dXcItVxEKr7M303SDe+aoHJiUWb1lJGCN7vrC2sZUsPyiWiBcBn+773xIZeldmy3MgBBWivCpZSxnlWLyhpwV3meOzwbgCu7JEKyDLASoUgzjIlfXzSFEfkEqs2NIeX+GsAY3RG9MqQEv7UWRLTu7pEyoG3BkhCyAnJMtNs8V0h/P53feqQv2KhkLQ9dOLJvif9V38NDkvKUFPuiBU6LrmlH5VPjVp1WDseKJF5SGfjU0W/oNSz7C71OteW0we1czPs64RL2J7gn/ewdJ8cynrm63hwyPXv8UwspJCzQFirGLKSgBMx+UE13gke5ISZc8qsYWFTlLmM0NYnn2VnIcGOnytqM74Y9rXQopLNxEFL8vcCBmcmmxyfThW0z7VUeSoYlM3OWs+pk0xVr+jnEnuKaL+BjcXjYyAADfCwG6ht7WUsk8Bbpciyu50A04dt6qNrjzaTA==
  template:
    metadata:
      name: objecttypen
      namespace: publicground
    type: Opaque
