---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openarchiefbeheer
  namespace: publicground
spec:
  encryptedData:
    DJANGO_SUPERUSER_PASSWORD: AgBf2HRI00PnHV+EJN+b+ZXsGeQ+dVGt+/6paIrQRGOrWCYRfMa+39qMBAtmniCAW3vr8Bu4YCQ2jz3grLnH4tHjF0EoYKT2cux7rJsHo3KYBu+2DNapd7cI8sMwOOP3c6SHQcM+LO+eFL7gLm0ZS9mqJfo9ClOw8pFosyF+7Vz+DYLymma8ZWQ/l9vRwOctt5NWB8Vq985m2SBxyYi1cqKN5j7qG1zxWxiC41b+ae7ReU4CIS9jWc8oS4jLWR9MGVt/wImEqW1gWSyrmYwgHQ9Vv34P6vcw/2xS5wLNkTqCyhJiReovmxJp95loRMNaAd6i5k+xgvejL8VbZWdsvrKWF4e3nVBhYm76cC6sIeMRG9O/rThvmosNLOTUG6fqUVa6nbPa6mdt1PbCboDuzW1nNS4Ay4djgMw5cGbktE/Kfgc/YiMOU6PGSkDmtKWDtK+R0a635c1vapTVtmJdecemV4XTGnEG3MnYz9P5JWNw6mGHlG0CVf99Y85AVXYEZWD0Zdl+rGSxkU62HLm9WuYocusIXqaS3mNUTzMcOCcGcAlDsLuY88Ok/99xpWyKJdfxiea2Qzp8TAq720oDnWt1vylJRiDw+rY6ysYM6UhYdCqjss3wvi9OZufjvK7/XAxpWKJPkp3dZXTjTcnospJyYL7OaedLtLqq4v+DQnqa5Sk5HqanmbgETa3mfQ3k9RTNxMT5Mo94/A==
    SECRET_KEY: AgCpwF5Yc0Z25JG+WF0HfsrESsbJ/rn2Ggl8+zJVvTo314fC96PsRRo0qhwe/ZeHnMmPUhdet/K1Q0Xibrbi+ZiAPGfpXM167k3jXhdkI+stZlmdo9Piox3rv7x2CmJOvOvWDyL7o9RnqKr74XabLdcC11i56IAV+DNbTX9dJwhV5ssUtYyv1n7Q81ajiBFyIfpxNe0Z2vbwFb31E3ZQmcLqPMyf/6KrzLJEJE7UapI1KnQtM/ZqcDrHDNjfEgvtRtAhLli53fN7bqzkqmii8L7OsaKqyEaNmOSzOV/PIkWPQAOGgFMLA/B7BesSiPpwXh6AwNP34m9sfSAWafcuabCVNkmbDDib2xRpg1ONA5C4LaJp6GYwUDgexYP/VoIXcZuIbSx/OMBdIResnH6wxweWn3K6HBWuRSTqVI6G9NuolI9ZLfxkY7Ksl93ozp3sgPBEfvFDzjhaSu7S4ftcuz6VXbaeRfIXCz5IlNadJ+4zD//Zvgb1z4hUcV/T1MV6IenALbTwcBFWuPAbjypiTxw6TCSywrB8oNOWq7GeY4Ofg+jnBN7zz3ckos/5Twe47Zep5z++cMNhok3doM0QFu1ien76ADy2JKjhac6rYVUDRJ4754rsAg7peSKMIwZefV2xyee5itSEkQSGb1mS9S0OohAF9sFdi2LNjGzCHO5otsMwsPcFakDCU9J8hll2vkCa4U7cx0w/FVeFCd0ziTI0o4SJPc0c6QVSeQjf7ehDE/2pD6wh5+dCy64GORBAuinN6w==
  template:
    metadata:
      name: openarchiefbeheer
      namespace: publicground
    type: Opaque
