apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: openobject-pg-cluster
  namespace: publicground
spec:
  instances: 1
  imageName: "acr655.azurecr.io/ghcr.io/cloudnative-pg/postgis:18-3.6-system-trixie"
  storage:
    size: "10Gi"
    storageClass: managed-csi-retain
  bootstrap:
    initdb:
      database: "openobject"
      owner: "openobject"
      postInitSQL:
        - "CREATE EXTENSION IF NOT EXISTS postgis;"
        - "CREATE EXTENSION IF NOT EXISTS postgis_topology;"
        - "ALTER ROLE openobject WITH SUPERUSER;"
