---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openobject
  namespace: publicground
spec:
  encryptedData:
    OBJECTS_SUPERUSER_PASSWORD: AgB9x3r5DV/ggRQ4aJQzmrjCxtEj3zZiFq1rYyU73vH/cAgMlxvK2iUoNNI5xY+/JEu9Ag0i/1ti8zlw5CQZ085aPz5alEHgNHQYCmuffLhvvZMYim93ZKxJ27UZJo22adAQAi0AJzo274CXhDFpw5w1QQqnFoQVA9Y/ZpuHx8qfMgI+dkQhfw0YCKDn4FhJKjiPvqyTpjFFlNwlDh8xTrFjTAN+4eOHtuCNFL42Twbhj2JGFdiZsb4QrAfI31AwxUfUVQq7BUoPcVDTRqVXBa9uP/cDbr/V/2GWRpciG8s97ELYp/fkfCeFqZsJCb1SyCXMcIrMdxv1NbDY6FTpcydaoXnDeWqlPLvDd3Z5VdDaV09MgkXMJFw6wI0GUHln3xH3XnPF6GGpA6Zoi7ue3l/H0d44H44xaOJjrHz45PdWJjNEOwjWK1BW9lYuhhSWqgzBk3feCUZOwI+gJpPPB9LpjYCPHYTjUKojzi4RTrcW6+cVj4X5JtWlKirD0CGh7POU3xXr8i5ux+TCjchzBXQDeumUmSPsB168iCqH8Z+1+HXmqQJR4H3s1NdhzzkENhaGBb2e9NewWgYZCXCXHuIrZtoD8w7VVq7IUCp6/frDNNpFsaO0mY5JodnJlCKWNAeLFkeiE2AQMEf/n/p3lUWvmS9tMGBn4jm6oWqmLKC+4Oi9x9HZJz+7QrGQRnWgDHoVGbGhyLIuTMtVlwL9SAAMI2PWyziQKb4=
    SECRET_KEY: AgB/1ylFTDmuA4XmcXlJ+2b4emVnMGXcvs1cZm/z/B2NQopBQqInPCV/f6BSyqKYSYixP6ieomd2hYc2WAgYUsJqYo6rqIBG3IK+esd+gxDMS/ozugGBXN9kf5AfYKz2Gl8ADyWykCeYFDnerXsT+CpBZVujxPMdvypRVPmjpDqOzFA0UQrJRvTJ1HAjmhjGgGiI+8Ku+XaqmxNQzEMM+A9BT8NXsWC1AqS22waNNkWdQALp62V8usJpzisSKuhkeftV8SYkucFK398dU6bww6zgQDiq4xw9cvX0/c14Ua8UlPqogr6SL2A85nOGiIppRI72I5BBbW04b/z51Agc+q2nGmLmadZclekNUw2ht8d69iFmVZ1Hbd5P2yg0LXopN4/wVpci8/XApqrb3ZoHY8jgqmqe/WXLK9dSZKWFwZqvGkpItKaHhIprC/K0Xz+/xM2sG1+48xNljrrIBbsq/QWcTKrBxei8JfuzXLySvXY56CGFTxQTx4tG31BCzTMVpeQGkAZOLVkXIVvUeDHBolrCqh32HotPm/DBV+NQznYfNd7A2DhG67XfTpJIlxJzsbHiW9ecYLGj18bjpe2Re8DGOKi4gQB0kd0Gk+WJ3JehRnKnBaCF/4FnkleAqNhWqBf1pt/dkZkrU8ztWO7eDFR1tM6Zcg/1ttUM0jdc4GM4cuL/qn17Nfft/5RqREnHZyScZvhXj9R0W3jRcN1dr2Ter/fnWyJI18pINc6nGUYAUXd1u+ylJrRv8JdEzRnfBdmG2A==
  template:
    metadata:
      name: openobject
      namespace: publicground
    type: Opaque
