targetNamespace: publicground
type: kustomize

clusters:
  local:
    enabled: false
    path: "apps/openzaak/overlays/local/"
  655-dmn-poc:
    enabled: false
    chartVersion: "1.15.0"
    additionalManifests: "apps/openzaak/additionalmanifests/655-dmn-poc/"
