apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: publicground

resources:
  - cnpg.yaml
  - redis.yaml
  - sealedsecret-openzaak-config.yaml
  - sealedsecret-openzaak.yaml
  - httproute.yaml
  - autorisaties-job.yaml

helmCharts:
  - name: openzaak
    version: 1.15.0
    repo: https://maykinmedia.github.io/charts/
    releaseName: openzaak
    namespace: publicground
    valuesFile: values.655-dmn-poc.yaml

replacements:
  - source:
      kind: Deployment
      name: openzaak
      fieldPath: spec.template.spec.containers.[name=openzaak].image
    targets:
      - select:
          kind: Job
          name: openzaak-zet-autorisaties
        fieldPaths:
          - spec.template.spec.containers.[name=zet-autorisaties].image
  - source:
      kind: HTTPRoute
      name: openzaak
      fieldPath: spec.hostnames.0
    targets:
      - select:
          kind: Job
          name: openzaak-zet-autorisaties
        fieldPaths:
          - spec.template.spec.containers.[name=zet-autorisaties].env.[name=BASE_URL].value
        options:
          delimiter: "https://"
          index: 1 # Vervangt alles wat ACHTER "https://" komt

configMapGenerator:
  - name: openzaak-autorisaties
    files:
      - autorisaties/zet-autorisaties.py
      - autorisaties/config.json
    options:
      disableNameSuffixHash: true
