apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: referentielijsten-pg-cluster
  namespace: publicground
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 1
  imageName: "acr655.azurecr.io/ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie"
  storage:
    size: "10Gi"
    storageClass: managed-csi-retain
  bootstrap:
    initdb:
      database: "referentielijsten"
      owner: "referentielijsten"
