---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: referentielijsten
  namespace: publicground
spec:
  encryptedData:
    DJANGO_SUPERUSER_PASSWORD: AgBFZoTW3SrJU0vHvdwBE+fYrfMLIdNyKxeN6Zb55z6b6uB2CpkggZVyX1goJfeRxTx6KtOIxVmCTUHluzaDpI5xaORs+mkSYKUbmooMCPLdIKMUe99jtD0Mtfneapk9gfd/Q/4dE/bNcrqluNT3ZlSlD6VUsVnzmL4DhMM11qhySBzIpxseYbaeDRL2SYkowVc+x8t2y+5jizZE09jtxXKhRAm2Xao1DghhHZHyX/6OE1N2g2fst6Fao2leYY70q9m84pN5KddTSpnFDSDSZsgLR53uNFjLB4WmUw43CEDjix1fxMtvBo9/c9KDQ8J5DlIkDD9a68BN0i+2+RF5lrx6wgFC03Cgap95GkgOchxlq6SLEGHfhg36gC62EizQ7DApsCLM3ce2L9HC3CzYe7BATPvB1FIKtMiPNXHCWBOxGmBkmb8ncEfjryqNdNB4PXifaHPo5Dnh2MFb3KDq7mboP7VuPQac5rrHNsKYuX0zplh8DjzRxSrit17ssmljlLmp+77zMEmWmjW7XOPJeBHdoAQ8l/bh/d8h1t20L6VKE30A7Ba40dbp1x2ctsCSX0AOWOuCosLwaGIESEiKgOMQig8GDKlTMWQ+U7oeAg110tT2NE9uLgoYQhwkWl8R3aEQEH0Wjk9nx65PC4fprs46grpbiQuSPjtSDkndQPt2iy6cRnNY+hRR7ymsyeEDVsD7kT/PpTfchW+n0JE2hStiPBDzRMMQ76s=
    SECRET_KEY: AgAv7MAL2AMoMmv7OocgSRk6+CVW71KtTaFV95kzhTX4gZIFkQPaWbdbqqc4R6UxAvIiuIjh0wNQT8mm8CDB3TpywQxN/B4UgMoYrnOrfHgDpM1WocisMQAGvJJzuzZcGzs0zlpySqnbOZKt8DnYmpGTaAU/CxCt3kwd0LVzm7FVfkS28IMNgucl2Y5CIWogijMzWi9SGbmgyTbYD5RA5Ebmb7xYpHGoMQLOtIyUm3NUCiKLnG32z3Pzt1Ks0ZVBnSz1XDvry7OWxl/i5cmGtmD3eUW95/n12cr0jD5o3LMqDZfxJ8j+i48o001JXHTbeYOtMXZAmqFnQnNFF3sfYwHmm2uCRDnkRFf/sHeo0tvuhxUcXi/0bIHBBSISYVtz8dGxHq3RIHW3cWj9vKh/ZpMBUN4EROR+IzC7co/NrB79qsXLsI6Fru0ibyElI2lDz+IR9xAwEx3w1R5Rg+qACMkokTZRkMTfARWCusx2pdBc34hCaZEzyz9yTGQn7WpqyAkzSJ5RKOitw1wlS2w4P9NHlKYYMYpnW3xJX411ye32D+R0zamyZvSCxat6dMnAs9jtjH8lSoTf7kdhexwNLkxIWrFwK8mZ7aL4X1kGA45v3kal5DXbS5MdO956cK7UiK0q+vDSN7wPwkBKY3jxkPA1IUKWW6M2k9BZ6yl/8sxrSGKTZ+V610mk8jzzvkziEKuks+S6/5eerxS9iJ6q8YueYahXKIueBI7FKFFnUp62csMWi5aLd+QzK9R4rYHg1tos/w==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: referentielijsten
      namespace: publicground
    type: Opaque
