---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: referentielijsten-config-secrets
  namespace: publicground
spec:
  encryptedData:
    KEYCLOAK_CLIENT_SECRET: AgCMktLOJoEtwKpbHTNP1mmScUNLfm9IUmgDt3pJGjr7P69Hrzo4aO/vOaxHhRt030QQYjGJPRkchKjE5JEhuLhl1Ncq8jOszj9Uyb+R4SRIBtEIDewHjYN3zoxSmUCCThYPUxNEjSyr3BXxuIXd9HfhGryJqGPEp3Hq70SYDRmZiFlNNAt76EVe8y1Fem6I1N5Jzsdx+iFt8gZ3BT+VmSc+i+D+Sthf2fw8h2I6gSe2QtZjRvbISC8c9wCsD7/817mvsVXR0L7dlh9bK5Zsx9mOX5AihnCeDGfYAii85UVV03+S2ljoBH+MlvLMQTAOSXl7zGDoDUk9sH/9quQpYEEht3QUuRXrIyIfq6PcmzG9AI2QiFRGqLS2FjZpGBip0m2/um4BWeKKFTSTIQdkhibTyL11H72IrkLy9CEUgdrehIynI4PS6NPuJbDwbyzLLazUh1MCoQEZPXlDJsczcts594yCG5WAQ18fnM8D1D7ykVYtPlijuy3XdgUsaet8lmbsQfjaGdDWFbpyVYPSMysguJkh9C61zhPtUVoFWkaTxv0nfV1f3eNt2NcmgMDLQfnUZPSqyhkHXoC7SGxe3CBEQRM1acotHq5DK/pTrFbcdsbfMTDMUo2fBLqxoQyLv+K26EwIr9zpE8qg8QmLXu4TDYK0gQ45+3d3GunLd9K0lOPRQRp+I5h38wu35Cs3waSvJr5IvVLCoQBoOx+nDskwkszVqzeldeu0eDcglWJb5XMYsCGrpYPEqM7i3O/QhAHQ74k43HqGCNO86KELtDx7
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: referentielijsten-config-secrets
      namespace: publicground
    type: Opaque
