---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: referentielijsten-config-secrets
  namespace: publicground
spec:
  encryptedData:
    KEYCLOAK_CLIENT_SECRET: AgCErIS6b8KDNjGENHQRBMhZHdw3ymxr9g36jit3WSaBioZzf0hFUtJ1kWbVqKkWGa6W9OELO4KkdDBe9DXBFIDOy+cL+5qvpSqmdJXKu78DrfYsrJ6V5/JenIHTGr3HGuTEjuvC4byzKsSKA52FKo9TOq6XVH35ijlw8ck2ujJ4jl31xNFw6T28F0jtlbnhkwYuE5pBQRycttSqlvwrBe+xPETQt+OBVFIFdeR8lZyTyf6imafGwFmuc6vxlZyyQRyzqxqDh4H2LOksFaLpAAEkksRPNXTEhyP6z2GT4DRcwXQtzYHEPPHlu70Q9an4fnaw4mrTiI9Q68mQmBWi4SxGJYt1FD89MTx7vCdpu7kO2t4suahUTr1GFqAxwri3VfFphi7gWyRaB/Pwg/sfkWYXWRSBNs4jkNiywfVWTj9biT4SQ06+arRDyG+5xAjvT6lsRncjK2ZGI7uv8JWhFpVkWHeCJbQbjsY4E1CVn+bFz5R1q1dc1KXuibMxySjkkVGkqJWH5N0jXX2xcdYuxFCQT8K8fXkQcq0qmWabWI4hiyMVG3YdTt7hbZqhpewa3nFFElYjQ4gTbmie2q6lvKj+MK64G55abDDCXURUvOj/MdUQK1WyAoQRJtMvPmbFmc7lY4DXL//W8zdcDaqh4W9E/E1mnM1wZHY1kBRYn9eCGcnXFvQYXkPdHsTuv70t8wbPccJh2VRU0SZkURLCDTg5umaHbUhSJbN5JWfhLqr1JrJni74fa5Tn2bJoduuzWCDeSsCZZql3f7LHzqpDF5vE
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: referentielijsten-config-secrets
      namespace: publicground
    type: Opaque
