---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openobjecten-config-secrets
  namespace: publicground
spec:
  encryptedData:
    KEYCLOAK_CLIENT_SECRET: AgB1zZkBwW8Wq1lmZ6yD/3/ecD6TJhWJg5dW04Ihp0RMItbkAYXLVmK7vwBqbxULhMs0fdO3hegvMETE6FQm7t1lPmPpjnXIHb+76qzszsH8LF08AUzoBPiW4c6RQv4mB3cB2ArU6smviDHnDuMbyYwCplMRgFXzB60ITFtDSoLz4+hv7g56wdQXxRjwJclql+QMEEyWYS3U6TrD/nmu7+qPmBhGquiAhM7lxICYEm0TmcvwMFagXA/pSw/16cqiRQpgljLR6wxzLdIffuB8aYEhsD+jRFzgLyzDbslV6eV9tEAGSA4ykJS1zDuITq1hm4B5ieMyGMLggOD0wAYXmZlnxp4vEqyipOYhx1+2gPMr0m51vOwwz8vWvBBUZMapyBhbB3RiBAupjXMd7nyrbwhnbfbvu97qqolp7qpro2T6Ge8vUTPTZbzHN+Wy+3ZPww65dq4KhymB44Ol7ftQYYwFkGMMSyeutO4Zc2TMF2vvdRGwBV77Kk3Mvk5jkTTdaUd82RW9La1novDbUHechwmCRL/DpdhcDMurJbawqWzw7MZ6fdkE+HUeoDKgdU3XJzEXnknRYcGsy68C8iB+dNNJk2IO8mxnqkHNDQs48to5HVS/lOzZUFOjm26WNJ21k4qNImwMFQ49Bq5YdV2Ay385qJyd2nTW6xL6w/EsOCFbYd3lomvOuzNFkyVYX9ARCmf9zYaUXahNNgbA2EKXoeGKYTTjCOxqE+7K
  template:
    metadata:
      name: openobjecten-config-secrets
      namespace: publicground
    type: Opaque
