---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openobjecten
  namespace: publicground
spec:
  encryptedData:
    OBJECTS_SUPERUSER_PASSWORD: AgCfKsOnKqpo19H5SutfO7w0o5YISWnulBWRT3XcV4XQw7jboLX2jpSl4VdsGNplZXNO1pWmMMJ42xYnGVBGss++E/kyFPon9b39W3qRdjX2fBCbI0UxlJLI4i8M5FvTR9Se40s1/EtwJS+g4x/fhrkMOioIIP1ZvaUktNBIiUMbqRdws5R0vke6xuTXSA+iZRiVlkxgI1JNWYX4LYhondpSWO9mn9MZhItk8aIMhsIvG+tqSnnKcIhaPCXorZfxAuuQ1pBgAvxBGwJwh8gaeSriWBNPIg5UvRGyUsdM2MI497+N5cN6nwXXdYNURZ2dwl10j7z6vMQ4DIHY2VIsHmFh18iS7KldJkNrA+x2bZOI7osT6YoWdb38SBiB5VzNWxCtQ8gAUwFLYlEO0d2K9lE8+Iq7OUY+Q5UdzzLXeeQjcbXbZHksFqzuH2HNWqLqjTUgaEFbrLAdugmvJbqfwQu8nMMrX6ST7zRy5Tniv0PBySeGxCWR3XdqUkXfa3Sx3uwHaorpOEMuTfdShlz/HK+9qSRoRjEIVuqVRz7rFAN5OCZtXj0a19UPj0vdHmNirFaYDq2PWfl+R6zhQxD7k+PatL+/RtG3avjo4jE8njr++Xyei79B4vK7rfxSywCVE8zGmFeYz0mwF+jY0Tm4I6t//aXJ9qNrnYU6NvESsHiSGNKvZ2SwgneZVa7i93PnH9+CKsDi3+vqqw==
    SECRET_KEY: AgBfeB5tffAmTPAY8TWLIpqVEnJyLHJb7OqSxcJ9bVwLcAByFTvsiqBGnY6jcf23+2ckc4ASTMqQrnq5cn1gHxgdut1NK7syFqcX5eFEIkZiVYff+jbvYIS+1MxARpWAUxcUKKzQWBWOhJD1AKLXRnMUn+S9hpORiRKI5/8iSq0j6/P8jo2dq34DrFBpB0jrKDK/B5HmjoEHASsjRDU26u2iiAjm6xTQX3kX/ID/jLgrix7E8u6RmEv4aswNvE1jZmsKuiNYY9TeYGTROa4NYHT/zxfmsOFxsPMQnJcWrn2c9cSLHhJZopnCWcmX7yqxCzBb65yHJF2AyFpWHJHRDwtg8fHBZdabZnhwJeCXCs+grLFG16zNkH+tT3lB2KvKc+8U17xKkrODR0AzU/JxGpNj4C429gY6oDbYQtuCIaDVZphgXLiAfEpnFKqSGKMqx0j+uOTLyAGZ59hW5tdJ3mzaHWeMrfz06RbKia+ripamZwEkW7FAgq6tyHoF4XF/X/BxwqdbHJx7aP43qTZY6xTl/GyhCSgjvgD7+JCn/ti65EoLpaClNR2p4KwagyMs9wDzZlcGcMvXk4/YIME1FQf0XlBxcgGhzRvvos6GwmsH0CfTTysIv1PdQm2MSP5vt/VjLpj09mIalHntQwa6WlgukVUKp6N7SXdhCHsBbOnH+Mt6FkuyPqJuGPJjo0Z+BmEghD1NT1Ir0yPDFFxUVN2yNI838ubFOfkdYHudPwdQM6sj+WNEPOW0pF8hvNRN/1MzBg==
  template:
    metadata:
      name: openobjecten
      namespace: publicground
    type: Opaque
