---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openobjecten
  namespace: publicground
spec:
  encryptedData:
    OBJECTS_SUPERUSER_PASSWORD: AgBZdiLY4If6u9jzJQG3OMjFk1nbYRGt8nTjEyv73eDCssvn6TS5teJTSfdV9QDMEYHWtqrh+piCP69DWss6Nfe5qm/ex/cp3YdxQTmWgr8WkgcYvJYgCFEAHyBeyDzw+Qg8Fhdqkr2WOZhRmi0rhiZmaRTNkSWOduSlvafnUSBJeRLXn9M7P7taCh2qWFtNX2UcKvF/GE7UVQ4Opl9Mo7woGyaiCXGvAwfSicpUTLeCsT0KDT1QIuiJbbkNBUFwUhK0g3aQ/1/ZGJ9hNFOOoLuiMRHSFVw0DfHLAz9wb6BrMyLfWscF8bKNGWr2vOyjM0jTzMxiswxjPTAvfzOX7VxnqvNwW13XxvJrWmeGMJo4sbS9atgjvhQHmrV7O6RV1tThTI1w2V7CKJ0NHtOmLHF0caN08viMC3pG59LytJrpFEP5u/VS8Y5zcEUWaJQY1duCNlZnmmnQ4X/FJOPXjT1aN4Re25QQURdonrW85M0A4BeOBXK9oOPT+IaDW5YCFbs1G0DhoVoBX4h/cQo3UEEtapR0pDqentUmLbs/GDZs/CF8LqObMZzVoiYTZB383420X2EruDGGcCCSeRknD6ePuaKglAv98IHi8bI4Of++rP2iuMclXsVnPd8eBtbXsItq4jPLLTU3a1GspEhX2M9Yj1G4HeqzJpU1B+4AzgOaH7P+NVENXSrRGqy+GzEEZvknRr0EgTyv5Q==
    SECRET_KEY: AgBGr062lZ5jyzBZmtofz8JE5DY3M+HYfYQjxjNZiu5fldmaJ15k8VPt0bVOTR0r2TKpjo5zSUjxJ5DQm8HTQNuwUaf/u4HMcPef3xdfYatL3eMs9OfpVX4meL/RBWKvUvYmHLohR7GXH+zjpYZpOEaI2wtHgEXiSskPHqw4MlTgpSXwrIwA2zFAo5X+RUM0CzM5iM3JtIcnvfq7qGIOKF36OTFIyJ4n+QCyznwX6kgWZjxFVMX6bmmPR71DZJrk1+a9esHpYFX84nGCKNXI3mIIE9g6cDk2qYHmOmBNJ+tFbGLSXukDSB7iIF7U5Fm2bgjjm8ca+6vjUcxWVUeOIX3ialYaMGu1vlQlO1l8RV7F+XQG9+QZDAz+1puuQ9ZrmSn3MVrky7TG3U+nm315yc1Zoj8pVazF25JiPoswJvruAy6UQa8SA8jS31kl+B3byvIeI+dOH5/M9uaC93RPJCXXu3xSpaCq3ulsdZvpH7aL8KAcwq9ayzAuHcSHlIZ3qE2BalZMHSnWd+SM2jIVEnSKUhl1RUqJIcchoM0R00oofy3JkNTQHeF7oFhQL3FAnNRWmMSJOBdDqVyB5urJzbcX3XRZOp2eNZlgOSCeea651JE86ZR8EbT0/PcKQeDRsx7fyzkayWt0UGAcBxA93kA2LSrECdcPrqu3+fuWf+YqEasOS2ONvYn/MrhMMXIrXV0v9BA6lSqVkK78UgPDWmruUpAC6R249MPBR8RE8OjUYGSy2sURpRi9+pM/b3yqrR9TZw==
  template:
    metadata:
      name: openobjecten
      namespace: publicground
    type: Opaque
