---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openzaak-config-secrets
  namespace: publicground
spec:
  encryptedData:
    OZ_APP_GZAC_SECRET: AgBNm+1KNRIf8BEc6XHoXJLhDAI2hCrwHgNj+6PnMKqLTDTJYNReBRXxKpIhIQ/L5PxiEmMCOa6VhzheyJWVurPOVUlXpyeUl/8kH97DJhKJmu9SLAhGHe4fLzM4JAx2hV79Ta47vkzXHg9dTIJG95NIIbS6nT4DBZRpOePDby++BQ5GMNG5QBsjgddQQxBFtYD+C1qidhSGKi9iOHyPQ5ouzZClRt9LKtAVWbutsG006tNzoJLTh6UifUCgR6VGInyJhJ9PJKiVV9cNLMIYAnO1IGWyIAUu2PwYJPa7AJMpjuqu7xx7MBuNU+rHe1LUCODTK7EC3AOBiWib8IrtKt+Dfb2Il53b32gNtsF0MvR/Yl6OGygM6h/CrxE3OuWwgYgRB68Ohm2TBINZcxfbc/xHa71AMm1WxxHBSd1+toDzlsswfgkYS3PmE0HYXdbrgDTjpKxB1fCVRGEmz5ACXXGar7jonE7RjG1YIlbCw4SoymfKLGplThibNPFmivJCawszAhVKOjqR8jcwIQ7g7+Atn6wKFjx124jMrOSYXPR2Sf5+zPndgxqVdetXFtstrNzVpaXrAS82cYfZHo4pAfZ6QDA8VKHcYUvewr//+OGdtDKRmYuC/V1Z26sEuCG2VHpw2CZy46dtXZ387VWTgCTKp/i/y6V6j2n01nIc4R4KPIPZMNWIsZdfOH+emYp2dsKw//KoV8AZhzOhT58DcMgShkEEpHXjLBRu3u6Z51hwjHe1woXQ7oJM
  template:
    metadata:
      name: openzaak-config-secrets
      namespace: publicground
    type: Opaque
