chartName: openproduct
chartRepoURL: https://maykinmedia.github.io/charts/
targetNamespace: publicground
clusters:
  local:
    enabled: false
    chartVersion: "0.4.1"
    additionalManifests: "apps/openproduct/additionalmanifests/local/"
  655-dmn-poc:
    enabled: true
    chartVersion: "0.4.1"
    additionalManifests: "apps/openproduct/additionalmanifests/655-dmn-poc/"
