apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-dmn-poc
provisioner: file.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  skuName: Standard_LRS
  # storageAccount and resourceGroup are set per cluster in the overlay
