chartName: openzaak
chartRepoURL: https://raw.githubusercontent.com/maykinmedia/charts/gh-pages/
targetNamespace: publicground
clusters:
  local:
    enabled: true
    chartVersion: "1.13.1"
    additionalManifests: "apps/openzaak/local/additionalmanifests/"
  655-dmn-poc:
    enabled: true
    chartVersion: "1.13.1"
    additionalManifests: "apps/openzaak/655-dmn-poc/additionalmanifests/"
