global:
  configuration:
    enabled: true
configuration:
  enabled: true
  overwrite: true
  notificatiesAuthorization:
    enabled: false
  notificaties:
    enabled: false
  superuser:
    username: admin
    password: dummy123
    email: "peterdummy@wigo4it.nl"
  job:
    enabled: true
    ttlSecondsAfterFinished: "120"
  data: |-
    vng_api_common_applicaties_config_enable: true
    vng_api_common_applicaties:
      items:
      - uuid: 78591bab-9a00-4887-849c-53b21a67782f
        client_ids:
        - gzac
        label: GZAC
        heeft_alle_autorisaties: true
    vng_api_common_credentials_config_enable: true
    vng_api_common_credentials:
      items:
      - identifier: gzac
        secret:
          value_from:
            env: OZ_APP_GZAC_SECRET

tags:
  redis: false

replicaCount: 1

ingress:
  enabled: false

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1"

persistence:
  enabled: false

existingSecret: openzaak
existingConfigurationSecrets: openzaak-config-secrets

extraEnvVars:
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "openzaak-pg-cluster-app"
        key: "password"

settings:
  allowedHosts: "openzaak.wigo4it.nl, openzaak, openzaak.publicground"
  useXForwardedHost: true

  database:
    host: "openzaak-pg-cluster-rw"
    port: 5432
    username: "openzaak"
    name: "openzaak"

  cache:
    default: "openzaak-redis:6379/0"
    axes: "openzaak-redis:6379/1"
    portalLocker: "openzaak-redis:6379/2"

  celery:
    brokerUrl: "redis://openzaak-redis:6379/1"
    resultBackend: "redis://openzaak-redis:6379/1"
    resultBackendl: "redis://openzaak-redis:6379/1"

  messageBroker:
    celeryBroker: "redis://openzaak-redis:6379/1"
    celeryResultBackend: "redis://openzaak-redis:6379/1"

  isHttps: false

  disable2fa: true

  siteDomain: "openzaak.wigo4it.nl"

worker:
  replicaCount: 1
  livenessProbe:
    enabled: true

redis:
  enabled: false
