global:
  configuration:
    enabled: true
configuration:
  enabled: true
  overwrite: true
  # notificatiesAuthorization:
  #   enabled: false
  # notificaties:
  #   enabled: false
  # notificatiesAuthorization:
  #   enabled: false
  # notificaties:
  #   enabled: false
  superuser:
    username: admin
    password: dummy123
    email: "peterdummy@wigo4it.nl"
  job:
    enabled: true
    ttlSecondsAfterFinished: "120"
  data: |-
    zgw_consumers_config_enable: true
    zgw_consumers:
      services:
        - identifier: notifications-api
          label: Notificaties API
          api_root: http://opennotificaties.wigo4it.nl/api/v1/
          # api_connection_check_path: notificaties
          api_type: nrc
          auth_type: zgw
          client_id: open-zaak
          secret:
            value_from:
              env: openzaak_to_opennotificaties_secret
          user_id: open-zaak
          user_representation: Open Zaak

    notifications_config_enable: true
    notifications_config:
      notifications_api_service_identifier: notifications-api
      notification_delivery_max_retries: 1
      notification_delivery_retry_backoff: 2
      notification_delivery_retry_backoff_max: 3

    vng_api_common_applicaties_config_enable: true
    vng_api_common_applicaties:
      items:
      - uuid: 78591bab-9a00-4887-849c-53b21a67782f
        client_ids:
        - gzac
        label: GZAC
        heeft_alle_autorisaties: true
      - uuid: e7d02fd2-5a89-4a5d-b73f-d767d8ece22d
        client_ids:
        - open-notificaties
        label: Open Notificaties
        heeft_alle_autorisaties: true
      - uuid: c975302f-3100-438c-96d1-e00c79ef0bbe
        client_ids:
        - open-zaak
        label: Open Zaak
        heeft_alle_autorisaties: true
      - uuid: c975302f-3100-438c-96d1-e00c79ef0bbh
        client_ids:
        - open-product
        label: Open Product
        heeft_alle_autorisaties: true
    vng_api_common_credentials_config_enable: true
    vng_api_common_credentials:
      items:
      - identifier: gzac
        secret:
          value_from:
            env: OZ_APP_GZAC_SECRET
      - identifier: open-notificaties
        secret:
          value_from:
            env: opennotificaties_to_openzaak_secret
      - identifier: open-zaak
        secret:
          value_from:
            env: opennotificaties_api_secret
      - identifier: open-product
        secret: "testdeze"
          # value_from:
            # env: opennotificaties_api_secret
    sites_config_enable: true
    sites_config:
      items:
      - domain: openzaak.wigo4it.nl
        name: Open-Zaak Test
    oidc_db_config_enable: true
    oidc_db_config_admin_auth:
      providers:
      - identifier: keycloak-provider
        oidc_use_nonce: true
        oidc_nonce_size: 32
        oidc_state_size: 32
        endpoint_config:
          oidc_op_discovery_endpoint: http://keycloak.wigo4it.nl/realms/publicground/
      items:
      - identifier: admin-oidc
        enabled: true
        oidc_rp_client_id: openzaak
        oidc_rp_client_secret:
          value_from:
             env: KEYCLOAK_CLIENT_SECRET
        oidc_rp_scopes_list:
        - openid
        - email
        - profile
        oidc_rp_sign_algo: RS256
        oidc_provider_identifier: keycloak-provider
        userinfo_claims_source: id_token
        options:
          user_settings:
            claim_mappings:
              username:
                - sub
              first_name:
                - given_name
              email:
                - email
            username_case_sensitive: true
          groups_settings:
            claim_mapping:
              - roles
            sync: true
            sync_pattern: '*'
            default_groups: []
            make_users_staff: true
            superuser_group_names:
              - Admin

tags:
  redis: false

replicaCount: 1

ingress:
  enabled: false

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1"

persistence:
  enabled: false

existingSecret: openzaak
existingConfigurationSecrets: openzaak-config-secrets

extraEnvVars:
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "openzaak-pg-cluster-app"
        key: "password"

settings:
  allowedHosts: "openzaak.wigo4it.nl, openzaak, openzaak.publicground"
  useXForwardedHost: true

  database:
    host: "openzaak-pg-cluster-rw"
    port: 5432
    username: "openzaak"
    name: "openzaak"

  cache:
    default: "openzaak-redis:6379/0"
    axes: "openzaak-redis:6379/1"
    portalLocker: "openzaak-redis:6379/2"

  celery:
    brokerUrl: "redis://openzaak-redis:6379/1"
    resultBackend: "redis://openzaak-redis:6379/1"
    resultBackendl: "redis://openzaak-redis:6379/1"

  messageBroker:
    celeryBroker: "redis://openzaak-redis:6379/1"
    celeryResultBackend: "redis://openzaak-redis:6379/1"

  isHttps: false

  disable2fa: true

  siteDomain: "openzaak.wigo4it.nl"

worker:
  replicaCount: 1
  livenessProbe:
    enabled: true

redis:
  enabled: false
