---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openproduct-config-secrets
  namespace: publicground
spec:
  encryptedData:
    KEYCLOAK_CLIENT_SECRET: AgC6oIAlMfKGBpzX1QN8M4zkxEcsq96nVRxrZqTPCwHQFMSSWdbK7p3hTUtmB3uuG443a8PWyFJja9Vu1WW5pjyJ1JP0Hika5cOEFvRppVYBAOrdzgQN4tfDCO5fQtVdQg851WkPkhyYzSyvR2ZQ3FmvtfFbA4/UtuEURT8kYH2YQydWE67hVu45xh8D4OteuNW76w6g/XBTqWhiHGoGtJr5O1xMBdUS3zs+jqAxL9gmcDBNAYB9WyQDs+wzQH/YmgTbSOxoOZrBQ9vBixickSYPq4YkAmpZz2cn96ivN9Y5DKOznetkFJwNp8J1ur1FWmIWb/t0pRKxWOV/o/nnPNVRfQ2PNne6Mk5qQfG3Y8CEAtYJFeqWmdkE79M8SlvPYdX9sdlyJzpD6f/ECY+WG1HFTbotv/R4FxrSDgryrKzcNhmNvfgHPHQ0mI5eC43yu6oKfZ1pVOaF3N4letEYuBizsDHXOOMdSKowci0Iv5p3Ow4Jbc2PDYfEcJyQLiTbf739dFDSaxkzdl0r1ZX7kGNWCVFT5EjhXLdc4+ny/p5c4Z2RNNP+Q2zsD3V9OPWLA0RG1BXqQhIWYuV91fgbl7PV1qMsWkf86UjK4Bt75glUOc0yJiWQXlakjPsmizxE6EIYE37bObCP5IgB6yzPRxKq2XmSQ6WW1qnFI1UhLx5+tgRc+en61KUejawX9v5oJ0iKM5ekxDkPxj48rL0QmyG3vu3LnXobCvvR
    OPENZAAK_CLIENT_SECRET: AgBBCPQlxw0qBAcVulsSPUoSIDje5tZk8On+ptPXY/7F1YoTGToFVNTsAUKH09nSZyYIMOuT8d9PLb0zFSfVYvSpV/ACRfs/uYSU9EBvMnVRVuGTJK54iPbcIBxQlnJ0ujpVvnD2LeVXLWJYsRnwgueH1nDSvsFU9MhWG11UxEYayQ+h9z8g+uSllHFA/cQwaN9xdN4GBFIupVlSNHxxuAwZPuBtfYaU4If/L0RdYiJQTecpcpT2XV5stago2xfxP5oj+deKcTZoQfCQ8eJm84fCbfN/5lRlKiz8aH7f2cEKywNLCwpWJJ/1EZKjO/v8ig02w7X6x/b/DvUDzfG2ZbcrTok4CI5tJSZtix8WLm/LJz/VxehnoHBWihXBXNhwZZsNEywScpfmA5ouUbs4k4a7yrOSnLVwlIj2C0o+0o17H3mztcu0qdELkeJUzfFv4olasPw2R1/FVHx+oawNIlOmFcLVUI9FmDGyC2aG0PJf1kSlbDbh6oNlsFQz7cC6WP5+zDM25fCxmlCueVky5GXMTfwfxWPAXu6CJbtZf63RpuboxwNUFZgmwoDsdIIFxF4xnArh2ZLoK5F0GAcFX/S1Ywl7pU36KEclnEG1NlC0hl06AcBhIfLTRrS4p0KFY1msUg06xkZouSqeNRfGo3JZVbF91B3PCB8eTH64Y0qtAVoAobCWno6hIYlYFPvoLWUnNhFVQH2AzjAGvPXQQfnbwB+BpWE1/y3r
  template:
    metadata:
      name: openproduct-config-secrets
      namespace: publicground
    type: Opaque
