---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openproduct
  namespace: publicground
spec:
  encryptedData:
    DJANGO_SUPERUSER_PASSWORD: AgCB5W84i/XvIvRiVjbK9zIM2Iit36QqQ5tclh2oOGtglDhVnZW+lAq3J/bPE4wtTrDZG8zERORgz0IRiEa1lnA8V0bkpuXFNIYpzuw3itJOSnvYlnUVFPsHTf8dQuEo2nmnri45vJ9HArZt/P57tHEOOWoSS9h817KbcAzCzBKzYLCfKlXlwCzeaI2yn5NVJGqlOSZ30pDMj6pA/Hra0AxciXm5zxRHsG8wV73L5ezkhKW3p52+ufLhkV81p1RxsznC2lQpbSwRgkmYZkX545KALSFoEBXnhE70NiAtyHhqZ2TczBl4mj9konVp1nC0qfTM2Da8VIWCLp7hK0eqxy5IGQeNAGJcOrrFJoJjsLmHs6Hghvn8AWeCXVliJSSzVZ1M0gLiOY4KXNXbbxKkPDcSPJyrFgTSY/sH4KYhZ9ylQh1cmfiHWRFemCuKVFaJgvB4N9JKUpqeFXxHqMeY961GzO1L/Qiokwf/OhzIfxOQpbwpGB+l9iEWnp9BmO3ObXT7gd66JLhBV++eGwfTbKECtxAxzhFFw5CRcJlm52B/nNStAeY2JB/MiIH8xZni8m1Jg7uj8ey1bH7tPrRRJsmpXbQvKamiRN3mjw5J15MKEC2HA9++kpceQxtHb504Dv/CSkSDBnhqArLsQoIk8peC7cPXahGspSQyR0x8VzqIX740mcWb8pC7L4ZeihnXSKcqq1+cmvEk2A==
    SECRET_KEY: AgB5p8rqJuJ/VttH7+cJS7TSScsgka3zJuA39bXdUz/IGj+0lUSvcaZyF0akcgoekg2sKO+tLrcpN/3mtlQLU++fqRSJkIItqmSUnYg8ucNmAOLYVNOWAS5lQ6G+XdAKqTZPNwWaYqzt6yI1D/SGpkrNTTZsdXOAwVhCsiOIYWGFgaLwrA6nFun+cBWGQIGc1kZAehVQeUh45fkZ2lzcyoKrd4qGMEXUG7a8GrhDlIvgWaaqReBxKupI7MefHxWDsOTr6c865onMsy0ZubGU6W7TR5TFnEi85IVS9MdMyGbrT3oTGw3op+albyhhjGjth77tVFmwQuUajIcZvtUIqz+GKt9+hgqTNJqN0cTSZjH7F5Lc+G7MTmgZSt7Rue/l00hG43fwyzZT90RpSlrMQhILRDcLZiUdXRqV37OdUxigKLGG3Oj2MxAm5PlhzwsQk+shXVwJ3+M/yF7TA7XLyLkaeTbXHIN76CGth5SWOXCHiy8fOHj9S2qtEoqgWI4tPv6T5yK/D5kbuhahQ9MpREFNScnti3tYV1xr1QEBShYjRf5CkafsCyLlFKDnMjkqQQNEmX24j4K4Qi+tRnDV/M0UHv99A4jswyo4u4VjsZ0Lwg430mkE89t3ykRhg7PfMCyVxWCFKr65fZu0d9lR4OKmslg6i5BmJO6jDNJalk8HwnP/1nksQlRHVfbMen0tUdtF3QKuYbzEm7KU34YYN1O4lsC5UZRLh1RFuS+4mIzy5lcyjmMI971KpGurzqslHZVdgg==
  template:
    metadata:
      name: openproduct
      namespace: publicground
    type: Opaque
