---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openproduct
  namespace: publicground
spec:
  encryptedData:
    OPENPRODUCT_SUPERUSER_PASSWORD: AgA/lS9ximB/X4xu2msor5qPjaTT/xg5WIvv/d338VyPegfpJHCrUPpnFIRQvol+Wv8NEJ2owL2N+BAN4+tWgHdZpyrmJQoCrPmdOhr7PWQr/ad0yJ7XRp7XXqcLDWSf4+IA2YCQ/0ewYr3+CBxH6pJgQuxDbCJMrZbDHt62G/qun5V4GAOMB19z7Z6wS/RJYq+2WU68Jwb5MtwAHkh8rLXo43jtAEm8AdTr6n634bnSaryY0q1151DKPUD3d/TG/z/Zew7fA8ub2k8wsHYE4blFKtdTkPstkjgOJ1VARNRAEP/d12UFm4wBY+q7FpK3Vya2vBMaVURafnjnSru2fonZfugJH7lIUcUQ3sK9DimC/+6LYxOVF9rOp98984t7t3JO++mgOtQ5vvD6n8XvA/3jRdh9ZemAnrZbhdfwzBudt2I5qtF2Gma1RbRNkBL75K9SyqTbLAkKd+K5zXQWaz+7ICwXzx0NBwMiP8SpHDpQXQG3I1AAJcIlSEP90JA3nxrDXJ/BgDnHkDJaeSJ1rzr73AHTD8gmJrsHTFugXJRT5/Jj2QSsyj00EbBSQ3w56j00x7wJJ3YSzzEtuoHcaksX89SeCIfUIQqCBhK+9QYhT/+IjxuXiKsvt9tr1c6kGHKPQK45B7wDrxrfVphoP9cx5St//uoDE2Ydp4quojbv4oxmM2BftiV7Qp+8jPJv02heC2jSxI54Tw==
    SECRET_KEY: AgDEXSZBnGEFZ0s2eVK4rr0gO06+f4SmBoOFhWejFBbE+34EIGoK37q58Hu/jZGsAE9G47LrOTuwiTGy6Ef5Yyh7n1Jt527h0l61H6FmEHcO3Ilj/nfmRMABD7cBJvlBY+JkCRa3rNlRJN1SynfiM9DV0/LWI20lktjQo5BkxzGJyhCNJTo4Mn/MH2cskfSQZCBzwd0N02FNjotDecSW5rUxj18EQpLjTb9OiEtEcXYJAkHl4hWJleCI0Rag9U106++1vcCzEf+TTWCOqSpNScNBp640B904yjPHdaMJAKzQX9lQk9xMhZgAgOxvJjrrAezIjcVm+RH0suwTWAfhKpW7trQoXKYZRcA9ZGQqvR7sgYQDQlS1KMclDr/FuGTs+i+vikd7Hh9XuFvuKpVNNG4GSIq5BTviMEoWW77lw1z7UXcIywqjJjf0DTeQ92XUi8cmpIJXYrFRqh319bUaSJKlxq6yUUoFgRNWOKIVFSVICFvY7WTfDrDh0vzEfhs5MZ2w3TEMABevMKamvQ0oxJzF68Los6F8UmSBlbXvo1JwOMUT39+m3E31yQehFFGAEf3veNUfQfkbjxHCloEYJjwhq0OnTQCMZMMC3XjhzvHghO8JBwYEaCh/eMxgwwoG8iwkYGGyTo/TzTluNrvuiqCGt1wQ3wKUnlQeohmqKe30n4SwtSBPuFM0xEdqwPCVRpohme6wlkZZZoJ6+yg2gzLx6Bt68uXDLFT+FXKB+ihm/wOGKCCPjLDfqMqPLANwTH1fdg==
  template:
    metadata:
      name: openproduct
      namespace: publicground
    type: Opaque
