---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openklant
  namespace: publicground
spec:
  encryptedData:
    DJANGO_SUPERUSER_PASSWORD: AgBk+jKmIcSXFHs6C3uJsIHTGZdF8XO2/4MvooNfPhjhrtNUAQuQa1Rnjr0mlSXemaOf4FSOSVHvDd5XZORQ2gLvRYJf44Z5cw7rwGEQJUaSepTn9eHIGqrtv6Lkk+aSsOOG/rF7WoAERWea/0tQZqQZYpfLVOA78nIZBxTM1RT3Uc3JwnWQCetZ2qP5f+gIvrgRDq69tS0wug6BmKqKSFz15JlK8yWg8tmjzl0p7e8nITRgDSl7YbOms6UlcTjiYk7A/0oIsfIi/kuw/w5FLsUSCcVlS93deUoZt2qQxNAYKPmDakQLqUGKbWor6zpriUyX1TyeZ2GyZU99h/VU0Vas+5qUe5s09TOmCu7gFbr4/LujfJMKufF4qKVjhfDhwyq3zdyVfM7S5f2KbbINMgB9BwIYDeDhHh6UZJYZwqwl/Pv+byjurd+Jw5LjvGSEkw99qdAU7aCvyzDe7qzx4eveeL0U6DOR+qFUaYOXp2BZkQyKYlyqE9IUBr1R+118nfoymO4ts/Pk3yI1j01K2t4tgvh1S91OfjVNMZEDHGzFT6AoK/oaUSxZUN519ssiyWr+XjaSZ4q1Zxnq7XDoBO0zGbd41VGxX2tjwpOMPsjhqbrncqcKqg8e0WfX0nCyXOgbI445MWEipyeFAtBFIqvJc5fjJJQDWAidUzXAXT/idNS0oFFcYoUhqJkbTeUny5rT6fuviD5MaA==
    SECRET_KEY: AgB9coK1P7nSrcUOJEWWtamAZxabJMQpX654CWHG9hZcB3HqOUhmeT8lwb+Yss5QDbWtucXqvA4sweff37PICxWq/R7JhMSGWVcd+UnE6Q2NFZ1HGgvW5pt+x3ZPACXP/XbxDDcMKbnPMTuJDQPIRim9SQUGuCo0G1W2YvldKwz5jzjVy6rPHML6F0c8I1/9N8XzDdKJPaJIYBKxr1Fe4Eq3MjR/7uKGXMTGpFbdvohkNTzjvH4uIxM7qOFsY4FwZynSGvF8g/5fiZYkO88U/hgF2SlfFxMyjZW7KFBG1g10/tjAiAjcyKJNVg/6gF87IFcVTyn2Gsq+b/KJ5DYLGtffc7VEtUP3XQDvCZeewIAH93VCv3C3aJ5YGZ7wagwOYD+YENPFYsoKqDhw50o7xa5eaeYAZZxbda1t49bwHx/JfSPPCH3b5MLCZv4MvKs4GrJLS6s9grF9631tRZdTGfs2zoadKMz3wfl6Jj29QQDy8r5sFGMB2/LDzmh3b+AhtyOqjcEvGSerpSw3g0VMfKJfaSlcEkFZTDElW3msfVARmFxWY30Y5OEPlhn/hL8yreCrw2dWnjS0fjs+cmedie9plsX9dUyp1SY0eVzjOckNDhE/3QFNJxtj0VoQKbebEZNqwC7uSGoJl27kqltnnUPSzjv/nSmHYrQj+Ty+HQBclSsHB2iPGtUOs6RdxvqRIMvxhMbpFvMUwmT13wLV8R/zBuLPFpyIVaGuxKf2/qisEiPj0AjiUHB4hoJO1CXHNf2aIQ==
  template:
    metadata:
      name: openklant
      namespace: publicground
    type: Opaque
