---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openklant-config-secrets
  namespace: publicground
spec:
  encryptedData:
    KEYCLOAK_CLIENT_SECRET: AgCRgrf1BfS2qkTlPSzqZnnukShLIirsuFnSFkrHdrPv31wZyXParRLrzEEu1IXZ4+EBL69pIhliz/Hbx/HXMYirybHxCUjR+3CwFVxUPtSt1r9eju2tNGAJbpTf8cLGjShr7zSFZnNRV0a5pTknkApbcMdxF36cjVZ1PVYNuJD7U51I6C1wRDtVdt6+CtHvRXWjN9BkucL5wtsVpOy4bzK550pha+/Peo8mnywHzH/kphuH40MrU4SH+2amFZzqBYCBjM8qQGYQKjIy7Ah3l3nOJo/nsBns3RNVLf8SG8zGxTkWGkf/cjGJmrig5WjRLzK4c3M7qZmG5GX0MAx6hNS1rFsVxcL6hZB6FX8QF5QkoLrccu9Jq1XPSGM6Ho7JAc15VI+Ikftz+xonAJmmu9va36PIb3Hqz6PwqDpmjbIRYmTc7WPRYxe4ICGnixLSCYxmBLmlm7iNQpXigG9m30HnYXxrakSt72sOz4N5L4X7xUshgpmR0UJXah19WxNZr7aZMHsvqoGb8QOoTO8By5jQM4hzDeWLkVwiz+cSAu6UsyPI7STKqUKcGRKaxxwnKP9dMCfufjjryBSgnDk8kQ3r/cxhg3Fg1CozAYjCcNwH6qpAgkoqRFOEyqjbgk1eGDj7vap8+j0JRJUkeFkH6K7wn1uHgQdJd44ai28mzhYZtDbrsAOD27qMebZu43NF+ZDLYeKp6li+DEsetcCh/ciZ94MrP3Ly07LFmjLCo5mgqC2NqmNEV3B+0HZgHglweabkb/hd0ikjU5pmCv4fIGbd
  template:
    metadata:
      name: openklant-config-secrets
      namespace: publicground
    type: Opaque
