chartName: openklant
chartRepoURL: https://maykinmedia.github.io/charts/
targetNamespace: publicground
clusters:
  local:
    enabled: true
    chartVersion: "1.12.0"
    additionalManifests: "apps/openklant/additionalmanifests/local/"
  655-dmn-poc:
    enabled: true
    chartVersion: "1.12.0"
    additionalManifests: "apps/openklant/additionalmanifests/655-dmn-poc/"
