---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openformulieren
  namespace: publicground
spec:
  encryptedData:
    SECRET_KEY: AgAY2F1Y6NBQgMh1fkNcPkHbqPuTdMgUFDbJ9GYvqyOAhnOM7A0+vD6PsxA1ZHSCeh0NAXwHjcxC3wQxNlVDMISHbRKTViRTAW39DSpzO3me27lSX6HnUQZRe7VzsT3wc3ZSrhGMVjJBBbdxlvw7I3pFDUCxdd91yXvKkVgoTrbSEtOk6oyB+de9vBmYtn/bTq0ARRzCebRcpvlWb9Hbdw0ITXvAQZyfvbLv2YNoJsnLhhnHTlKNaZs/63I3tYuf12hzfu51x/kNTj+/L/Pcc77nPHwRgNZGb/9HPlg1G0AILqtQIbqz0+pbqPtmP7cCVMDpv37azmFUWVGLDLesqldeZSqoQGKaNQHPKRcZz3BBdJH2lnPtG8Dhc/5o6ZrsAXSaluZcBNTNT/pDinuYJzoH6M/57r9jC985hFlJ89W4+HbhTHBWR3q9svzm4xzROmcnn5kxIShfg/KEOb/bkcw3M3iHvK6EzjWc0ctdF6O+oqj/MACzi4Tbu5nJuQgnH9QEAxd8GqB9YYmY1la8oa2bpUIr1CFv7cDxiIDkrfVMPxzqI84B/rZsy5BzshDtV12yJyrG5/gHY2Ign9uIsyC5TerLOTH0CYmS3iVIam3Czm7hPjEJ3o9MGWJ46Yn0CH+jgP+tf6R4kcmZly3hQ6kfTE/kjmpy7D+/sDVdaaFcLlQbZkWRhD4dnEbs6IeGnlFYyaKgpqn4Up4mHrp5yqfvcps/P1R34ZyR5ExnrUC5/525JsMuvAmwie++8LQp3Lr+gw==
  template:
    metadata:
      name: openformulieren
      namespace: publicground
    type: Opaque
