chartName: gzac-backend
chartRepoURL: https://generiekzaakafhandelcomponent.github.io/helm-charts/
targetNamespace: publicground
clusters:
  local:
    enabled: false
    chartVersion: "4.2.2"
    additionalManifests: "apps/gzac-backend/additionalmanifests/local/"
  655-dmn-poc:
    enabled: true
    chartVersion: "4.2.2"
    additionalManifests: "apps/gzac-backend/additionalmanifests/655-dmn-poc/"
