tags:
  postgresql: false
  keycloak: false

image:
  tag: sd-alo-backend-925abf46-1779802620

existingSecret: gzac-backend

extraEnvVars:
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: gzac-backend-pg-cluster-app
        key: password
  - name: LOGGING_LEVEL_ROOT
    value: DEBUG
  - name: AUTODEPLOYMENT_PLUGINCONFIG_SUWINET_SIMULATOR_BASE-URL
    value: http://gzac.wigo4it.nl/ws/
  - name: AUTODEPLOYMENT_PLUGINCONFIG_SUWINET_SIMULATOR_BASIC_NAME
    value: wigoadmin
  - name: VALTIMO_WEB_CORS_CORSCONFIGURATION_ALLOWEDORIGINS
    value: "*"
  - name: VALTIMO_WEB_CORS_CORSCONFIGURATION_ALLOWEDMETHODS
    value: "*"
  - name: VALTIMO_WEB_CORS_CORSCONFIGURATION_ALLOWEDHEADERS
    value: "*"
  - name: VALTIMO_WEB_CORS_PATHS
    value: /**
  - name: VALTIMO_OPEN_ZAAK_CLIENT_ID
    value: gzac
  # - name: JAVA_TOOL_OPTIONS
  #   value: "-Djavax.net.ssl.trustStore=/app/certs/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.debug=ssl,handshake"

ingress:
  enabled: false

settings:
  spring:
    profiles:
      active: "dev"
    datasource:
      # -- URL for the postgresql database
      url: "jdbc:postgresql://gzac-backend-pg-cluster-rw:5432/gzac-backend"
      # -- Username for the postgresql database
      username: "gzac-backend"
      #   # -- Password for the postgresql database
      #   password: "TOPSECRET"
      #   # -- Driver for the postgresql database
      driverClassName: "org.postgresql.Driver"
    jpa:
      properties:
        hibernateDialect: "org.hibernate.dialect.PostgreSQLDialect"

  keycloak:
    # -- URL of Keycloak - Required
    authServerURL: "http://keycloak.wigo4it.nl"
    # authServerURL: "http://publicground-core-keycloak-service:8080"
    # -- Keycloak realm - Required
    realm: "publicground"
    # -- Client-ID to connect with Keycloak
    clientID: "gzac-backend"
    clientRoleID: "gzac-frontend"
    publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvSFXvj5f7wVOPvR5qFjLlsxHxlaeCD83F6z/O/6vc2wkJkCRGIdkqdJYKW2SWoibgd0tWPAeD4O9AKisyBO+MprfEyNTpaypvzb1Y49NVTg8gatdbV9V27d7mZJTnmViXUZF+U7eE4zHsuAQ9vVf3S3hhZhIGIhsLKMJI4yaJUQMlGSWHc6h17BICiYursn46OXu0SEmp6/C4A6TjqIhCON1x234Ky0KDZMZ05ttaM+G/rqcDCP0UrfnEmP7cGblVPH3xEGZN0pwrxXNRYv5DS7lL624Y0x7Zyq5rYwMfBlb4ZtlwjbckbL2kVZx53YOJxTwoGyxUqpsbI6WEyHpUQIDAQAB"
    version: "26.5.7"

  gzac:
    # -- Type of database to use (can by either 'postgres' or 'mysql')
    databaseType: "postgres"
    # -- Optional: The hostname which exposes gzac-backend
    # -- Defaults to https://<ingress.hosts[0]>
    # appHostName:
    # -- The port on which gzac-backend is listening
    serverPort: 8080
    # -- Encryption secret
    # Or, if using existingSecret: `VALTIMO_CONNECTORENCRYPTION_SECRET`
    # connectorEncryptionSecret: ""
    # -- Required if using Valtimo/GZAC plugins: Plugin encryption secret. Must be exactly 16, 24 or 32 bytes.
    # Or, if using existingSecret: `VALTIMO_PLUGIN_ENCRYPTIONSECRET`
    # pluginEncryptionSecret: ""
    # -- Explicit API URL. When unset, it falls back to https://<ingress.hosts[0]>/api/v1
    # apiUrl:

    # -- Feature flags
    features:
      # Valtimo Drafts feature, see: https://docs.valtimo.nl/release-notes/13.x.x/13.0.0#draft-versions
      drafts:
        enabled: true

  operaton:
    # -- Default Operaton admin user
    adminUserID: "admin"
    # -- Default Operaton admin password.
    # Or, if using existingSecret: `OPERATON_BPM_ADMINUSER_PASSWORD`
    # adminUserPassword: ""