chartName: cert-manager
chartRepoURL: https://charts.jetstack.io
targetNamespace: cert-manager
clusters:
  local:
    enabled: false
    chartVersion: 1.20.1
  655-dmn-poc:
    enabled: true
    chartVersion: 1.20.1
